import {Component,inject,signal} from '@angular/core';import {FormControl,ReactiveFormsModule} from '@angular/forms';import {ApiService,BranchContext,errorText} from '../../core/api';import {AuthService} from '../../core/auth';import {Row} from '../../core/models';
@Component({standalone:true,imports:[ReactiveFormsModule],template:`<section class="page-intro"><div><p class="eyebrow">REVIEW BEFORE COMMITTING</p><h1>Import your records.</h1><p class="muted">Validate the file, inspect errors, then commit the complete batch.</p></div><button class="secondary" (click)="template()">↓ CSV template</button></section><p class="error" role="alert">{{error()}}</p><p class="success" role="status">{{success()}}</p><section class="panel narrow"><div class="panel-body"><label>Record type<select [formControl]="kind" (change)="preview.set({})">@if(auth.can('inventory.create')){<option value="catalog">Product catalog</option>}@if(auth.can('inventory.adjust')&&auth.can('inventory.cost.view')){<option value="opening-stock">Opening inventory</option>}@if(auth.can('customers.manage')){<option value="customers">Customers</option>}@if(auth.can('supplier.manage')){<option value="suppliers">Suppliers</option>}</select></label><label>CSV file<input type="file" accept=".csv,text/csv" (change)="file($event)"></label><p class="small muted">Up to 1,000 rows / 1 MB. Opening inventory creates stock without a supplier payable. Existing product SKUs are rejected for catalog imports. Imports create records; they do not overwrite existing records.</p><button class="primary" [disabled]="!csv||busy()" (click)="validate()">Validate & preview</button></div></section>@if(preview()['id']){<section class="panel"><div class="panel-heading"><h3>{{preview()['rowCount']}} rows · {{preview()['status']}}</h3>@if(preview()['status']==='Validated'){<button class="primary" [disabled]="busy()" (click)="commit()">Confirm import of {{preview()['validRows']}} records</button>}</div><div class="panel-body">@for(e of errors();track $index){<p class="error">Row {{e['row']}}: {{e['message']}}</p>}<h3>First 10 valid rows</h3><div class="table-wrap"><table><thead><tr><th>Name</th><th>SKU / phone</th><th>Brand / email</th></tr></thead><tbody>@for(r of records();track $index){<tr><td>{{r['name']||r['reason']}}</td><td>{{r['sku']||r['phone']||r['quantity']}}</td><td>{{r['brand']||r['email']}}</td></tr>}</tbody></table></div></div></section>}`})
export class ImportsPage {
 readonly auth=inject(AuthService);private api=inject(ApiService);private branch=inject(BranchContext);readonly kind=new FormControl(this.auth.can('inventory.create')?'catalog':this.auth.can('customers.manage')?'customers':'suppliers',{nonNullable:true});readonly preview=signal<Row>({});readonly busy=signal(false);readonly error=signal('');readonly success=signal('');csv='';errors(){return this.preview()['errors'] as Row[]??[];}records(){return this.preview()['preview'] as Row[]??[];}
 async file(e:Event){const f=(e.target as HTMLInputElement).files?.[0];if(!f)return;if(f.size>1000000){this.error.set('Choose a CSV file smaller than 1 MB.');return;}this.csv=await f.text();this.preview.set({});}
 async validate(){this.busy.set(true);this.error.set('');try{this.preview.set(await this.api.mutate<Row>('/imports/validate',{kind:this.kind.value,csv:this.csv,branchId:this.kind.value==='opening-stock'?this.branch.id():null}));}catch(e){this.error.set(errorText(e));}finally{this.busy.set(false);}}
 async commit(){this.busy.set(true);try{const result=await this.api.mutate<Row>('/imports/'+this.preview()['id']+'/commit',{});this.success.set(String(result['rowCount'])+' records imported.');this.preview.set({});this.csv='';}catch(e){this.error.set(errorText(e));}finally{this.busy.set(false);}}
 template(){const header=this.kind.value==='opening-stock'?'sku,quantity,unitCost,imei1,imei2,serial,reason':this.kind.value==='catalog'?'name,brand,category,hsn,taxName,sku,barcode,ram,storage,color,serialized,sellingPrice,mrp,warrantyMonths':'name,phone,email,address,stateCode,gstin,creditLimit';const url=URL.createObjectURL(new Blob([header+'\r\n'],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download='invora-'+this.kind.value+'-template.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);}
}
