import {Component,inject,signal} from '@angular/core';import {FormControl,FormGroup,ReactiveFormsModule,Validators} from '@angular/forms';import {ApiService,BranchContext,errorText} from '../../core/api';import {AuthService} from '../../core/auth';import {Settings,Row} from '../../core/models';
@Component({standalone:true,imports:[ReactiveFormsModule],template:`<section class="page-intro"><div><p class="eyebrow">BUSINESS CONFIGURATION</p><h1>Your business, on every bill.</h1><p class="muted">Invoice details are preserved when a sale is completed.</p></div><button class="primary" [disabled]="busy()||form.invalid" (click)="save()">{{busy()?'Saving…':'Save settings'}}</button></section><p class="error" role="alert">{{error()}}</p><p class="success" role="status">{{success()}}</p><form [formGroup]="form" class="settings-grid">@for(group of groups;track group.title){<section class="panel"><div class="panel-heading"><h3>{{group.title}}</h3></div><div class="panel-body form-grid">@for(key of group.fields;track key){<label>{{labels[key]}}@if(['address','declaration','warrantyTerms','returnPolicy'].includes(key)){<textarea [formControlName]="key" [readOnly]="key==='warrantyTerms'" rows="3"></textarea>}@else{<input [formControlName]="key" [type]="key==='email'?'email':'text'" [autocomplete]="key==='accountNumber'?'off':'on'">}</label>}@if(group.title==='Tax registration'){<label class="checkbox"><input type="checkbox" [formControl]="registered"> GST registered</label><label class="checkbox"><input type="checkbox" [formControl]="composition"> Composition dealer</label><p class="small muted">Non-registered and composition businesses do not collect GST on these invoices. E-invoice integration requires a separately configured provider.</p>}</div></section>}</form><section class="panel"><div class="panel-heading"><h3>Business profile & financial calendar</h3></div><form class="panel-body form-grid" [formGroup]="profileForm" (ngSubmit)="saveProfile()"><label>Trading name<input formControlName="tradeName"></label><label>Business timezone<input formControlName="timeZone"></label><label>Financial year start month<select formControlName="financialYearStartMonth">@for(m of months;track $index){<option [value]="$index+1">{{m}}</option>}</select></label><div><p class="small muted">Set the financial year before creating the first sales or purchase draft.</p><button class="secondary" [disabled]="busy()||profileForm.invalid">Save profile</button></div></form></section><section class="panel"><div class="panel-heading"><h3>Branches</h3></div><div class="panel-body">@for(b of branches.branches();track b.id){<div class="credit-note-row"><strong>{{b.name}}</strong><span class="badge">{{b.code}}</span></div>}<form [formGroup]="branchForm" (ngSubmit)="addBranch()" class="inline-form"><label>Branch code<input formControlName="code" placeholder="BR02"></label><label>Branch name<input formControlName="name" placeholder="City counter"></label><button class="secondary" [disabled]="branchForm.invalid||busy()">Add branch</button></form></div></section>`})
export class SettingsPage {
 private api=inject(ApiService);readonly branches=inject(BranchContext);readonly error=signal('');readonly success=signal('');readonly busy=signal(false);readonly registered=new FormControl(false,{nonNullable:true});readonly composition=new FormControl(false,{nonNullable:true});
 readonly labels:Record<string,string>={legalName:'Legal business name',address:'Registered address',phone:'Phone',email:'Email',gstin:'GSTIN',pan:'PAN',stateCode:'GST state code',bankName:'Bank name',accountHolder:'Account holder',accountNumber:'Account number',ifsc:'IFSC',bankBranch:'Bank branch',upiId:'UPI ID',declaration:'Declaration',jurisdiction:'Jurisdiction',warrantyTerms:'Warranty terms',returnPolicy:'Return policy'};
 readonly months=['January','February','March','April','May','June','July','August','September','October','November','December'];readonly profileForm=new FormGroup({tradeName:new FormControl('',{nonNullable:true,validators:[Validators.required]}),timeZone:new FormControl('Asia/Kolkata',{nonNullable:true,validators:[Validators.required]}),financialYearStartMonth:new FormControl(4,{nonNullable:true})});
 readonly groups=[{title:'Business identity',fields:['legalName','address','phone','email']},{title:'Tax registration',fields:['gstin','pan','stateCode']},{title:'Bank & payment details',fields:['bankName','accountHolder','accountNumber','ifsc','bankBranch','upiId']},{title:'Invoice terms',fields:['declaration','jurisdiction','warrantyTerms','returnPolicy']}];readonly form=new FormGroup<Record<string,FormControl<string>>>({});readonly branchForm=new FormGroup({code:new FormControl('',{nonNullable:true,validators:[Validators.required]}),name:new FormControl('',{nonNullable:true,validators:[Validators.required]})});
 constructor(){for(const key of Object.keys(this.labels))this.form.addControl(key,new FormControl('',{nonNullable:true}));void this.load();}
 async load(){try{const s=await this.api.get<Settings>('/settings');const profile=await this.api.get<{tradeName:string;timeZone:string;financialYearStartMonth:number}>('/business');this.profileForm.patchValue(profile);for(const key of Object.keys(this.labels))this.form.controls[key].setValue(String(s[key as keyof Settings]??''));this.registered.setValue(s.gstRegistered);this.composition.setValue(s.compositionDealer);}catch(e){this.error.set(errorText(e));}}
 async save(){this.busy.set(true);this.error.set('');try{await this.api.mutate('/settings',{...this.form.getRawValue(),gstRegistered:this.registered.value,compositionDealer:this.composition.value},'PUT');this.success.set('Settings saved. Future invoices will use these details.');}catch(e){this.error.set(errorText(e));}finally{this.busy.set(false);}}
 async saveProfile(){this.busy.set(true);try{const v=this.profileForm.getRawValue();await this.api.mutate('/business',{...v,financialYearStartMonth:Number(v.financialYearStartMonth)},'PUT');this.success.set('Business profile saved.');}catch(e){this.error.set(errorText(e));}finally{this.busy.set(false);}}
 async addBranch(){this.busy.set(true);try{await this.api.mutate('/branches',this.branchForm.getRawValue());await this.branches.load();this.branchForm.reset();this.success.set('Branch created.');}catch(e){this.error.set(errorText(e));}finally{this.busy.set(false);}}
}
@Component({standalone:true,imports:[ReactiveFormsModule],template:`<section class="page-intro"><div><p class="eyebrow">YOUR ACCOUNT</p><h1>{{auth.user()?.displayName}}</h1><p class="muted">{{auth.user()?.login}}</p></div></section><section class="panel narrow"><div class="panel-heading"><h3>Change password</h3></div><form class="panel-body" [formGroup]="form" (ngSubmit)="save()"><label>Current password<input type="password" autocomplete="current-password" formControlName="currentPassword"></label><label>New password<input type="password" autocomplete="new-password" formControlName="newPassword"></label><p class="small muted">Use 12 or more characters, including a letter and a digit. Existing sessions will be revoked.</p><p class="error" role="alert">{{error()}}</p><p class="success" role="status">{{success()}}</p><button class="primary" [disabled]="busy()||form.invalid">Update password</button></form></section>`})
export class AccountPage {
 readonly auth=inject(AuthService);private api=inject(ApiService);readonly busy=signal(false);readonly error=signal('');readonly success=signal('');readonly form=new FormGroup({currentPassword:new FormControl('',{nonNullable:true,validators:[Validators.required]}),newPassword:new FormControl('',{nonNullable:true,validators:[Validators.required,Validators.minLength(12)]})});
 async save(){this.busy.set(true);try{await this.api.mutate<Row>('/auth/change-password',this.form.getRawValue());this.form.reset();this.success.set('Password changed. Sign in again to continue.');this.auth.clear();}catch(e){this.error.set(errorText(e));}finally{this.busy.set(false);}}
}
