using Invora.Domain.Common;
namespace Invora.Domain.Modules.Retail;
public sealed class ProductCategory : Entity { public string Name { get; set; } = ""; public string NormalizedName { get; set; } = ""; public bool RequiresImei { get; set; } }
public sealed class Brand : Entity { public string Name { get; set; } = ""; public string NormalizedName { get; set; } = ""; }
public sealed class TaxRate : Entity { public string Name { get; set; } = ""; public decimal Rate { get; set; } public decimal CessRate { get; set; } public bool IsActive { get; set; } = true; }
public sealed class ProductModel : Entity { public string Name { get; set; } = ""; public string Brand { get; set; } = ""; public string Category { get; set; } = ""; public string Hsn { get; set; } = ""; public Guid TaxRateId { get; set; } public int WarrantyMonths { get; set; } }
public sealed class ProductVariant : Entity { public Guid ProductModelId { get; set; } public string Sku { get; set; } = ""; public string? Barcode { get; set; } public string Ram { get; set; } = ""; public string Storage { get; set; } = ""; public string Color { get; set; } = ""; public bool Serialized { get; set; } public decimal SellingPrice { get; set; } public decimal Mrp { get; set; } public bool IsActive { get; set; } = true; }
public enum PartyKind { Customer = 1, Supplier = 2 }
public sealed class Party : Entity { public string AlternatePhone { get; set; } = ""; public PartyKind Kind { get; set; } public string Name { get; set; } = ""; public string Phone { get; set; } = ""; public string Email { get; set; } = ""; public string Address { get; set; } = ""; public string StateCode { get; set; } = ""; public string Gstin { get; set; } = ""; public decimal? CreditLimit { get; set; } public bool IsActive { get; set; } = true; }
public sealed class PartyNote : Entity { public Guid PartyId { get; set; } public Guid BranchId { get; set; } public Guid ActorId { get; set; } public string Text { get; set; } = ""; }
public enum DeviceStatus { InStock = 1, Sold = 2, Damaged = 3, InRepair = 4, InTransit = 5, WrittenOff = 6 }
public sealed class StockUnit : Entity { public Guid BranchId { get; set; } public Guid ProductVariantId { get; set; } public Guid? PurchaseItemId { get; set; } public decimal Cost { get; set; } public DeviceStatus Status { get; set; } = DeviceStatus.InStock; public string Condition { get; set; } = "New"; public string Source { get; set; } = "Purchase"; public Guid? ActiveSaleItemId { get; set; } public DateTimeOffset ReceivedAtUtc { get; set; } = DateTimeOffset.UtcNow; }
public sealed class UnitIdentifier : Entity { public Guid StockUnitId { get; set; } public string Kind { get; set; } = "IMEI"; public string Slot { get; set; } = "IMEI1"; public string Value { get; set; } = ""; }
public sealed class StockBalance : Entity { public Guid BranchId { get; set; } public Guid ProductVariantId { get; set; } public int Quantity { get; set; } }
public sealed class StockCostLayer : Entity { public Guid BranchId { get; set; } public Guid ProductVariantId { get; set; } public Guid? PurchaseItemId { get; set; } public Guid? OriginLayerId { get; set; } public int ReceivedQuantity { get; set; } public int RemainingQuantity { get; set; } public decimal UnitCost { get; set; } }
public sealed class InventoryMovement : Entity { public Guid BranchId { get; set; } public Guid ProductVariantId { get; set; } public Guid? StockUnitId { get; set; } public int Quantity { get; set; } public string Kind { get; set; } = ""; public Guid? PurchaseId { get; set; } public Guid? SaleId { get; set; } public Guid? SaleReturnId { get; set; } public Guid? TransferId { get; set; } public Guid ActorId { get; set; } public string Note { get; set; } = ""; }
public sealed class Purchase : Entity { public int FinancialYear { get; set; } public Guid BranchId { get; set; } public Guid SupplierId { get; set; } public string SupplierInvoice { get; set; } = ""; public string Number { get; set; } = ""; public DateOnly BusinessDate { get; set; } public string Status { get; set; } = "Draft"; public string RequestJson { get; set; } = "{}"; public decimal Total { get; set; } }
public sealed class PurchaseItem : Entity { public Guid PurchaseId { get; set; } public Guid ProductVariantId { get; set; } public int Quantity { get; set; } public decimal UnitCost { get; set; } public decimal Taxable { get; set; } public decimal Tax { get; set; } public decimal Total { get; set; } }
public sealed class Sale : Entity { public string Reference { get; set; } = ""; public Guid BranchId { get; set; } public Guid CustomerId { get; set; } public Guid ActorId { get; set; } public string Number { get; set; } = ""; public DateOnly BusinessDate { get; set; } public DateOnly? DueDate { get; set; } public string Status { get; set; } = "Draft"; public string RequestJson { get; set; } = "{}"; public string InvoiceJson { get; set; } = "{}"; public decimal Total { get; set; } public decimal Taxable { get; set; } public decimal Cgst { get; set; } public decimal Sgst { get; set; } public decimal Igst { get; set; } public decimal Cess { get; set; } public decimal Cost { get; set; } }
public sealed class SaleItem : Entity { public Guid SaleId { get; set; } public Guid ProductVariantId { get; set; } public Guid? StockUnitId { get; set; } public string Description { get; set; } = ""; public string Hsn { get; set; } = ""; public string IdentifiersJson { get; set; } = "[]"; public int Quantity { get; set; } public decimal UnitPrice { get; set; } public decimal Discount { get; set; } public decimal Rate { get; set; } public decimal CessRate { get; set; } public decimal Taxable { get; set; } public decimal Cgst { get; set; } public decimal Sgst { get; set; } public decimal Igst { get; set; } public decimal Cess { get; set; } public decimal Total { get; set; } public decimal Cost { get; set; } }
public sealed class SaleCostAllocation : Entity { public int ReturnedQuantity { get; set; } public Guid SaleItemId { get; set; } public Guid StockCostLayerId { get; set; } public int Quantity { get; set; } public int RestoredQuantity { get; set; } }
public enum PaymentMethod { Cash = 1, Upi = 2, Card = 3, BankTransfer = 4, Cheque = 5, Other = 6 }
public sealed class Payment : Entity { public string ReceiptJson { get; set; } = "{}"; public Guid BranchId { get; set; } public Guid PartyId { get; set; } public decimal Amount { get; set; } public string Direction { get; set; } = "In"; public PaymentMethod Method { get; set; } public DateOnly BusinessDate { get; set; } public string Reference { get; set; } = ""; public string Note { get; set; } = ""; public Guid? ReversesPaymentId { get; set; } public Guid ActorId { get; set; } }
public sealed class PaymentAllocation : Entity { public Guid PaymentId { get; set; } public Guid? SaleId { get; set; } public Guid? PurchaseId { get; set; } public decimal Amount { get; set; } }
public sealed class AllocationReversal : Entity { public Guid PaymentAllocationId { get; set; } public decimal Amount { get; set; } public string Reason { get; set; } = ""; public Guid ActorId { get; set; } }
public sealed class LedgerEntry : Entity { public Guid? DeviceAcquisitionId { get; set; } public Guid? PurchaseReturnId { get; set; } public Guid BranchId { get; set; } public Guid PartyId { get; set; } public DateOnly BusinessDate { get; set; } public string Kind { get; set; } = ""; public Guid? SaleId { get; set; } public Guid? PurchaseId { get; set; } public Guid? PaymentId { get; set; } public Guid? SaleReturnId { get; set; } public Guid? ReversesEntryId { get; set; } public decimal Debit { get; set; } public decimal Credit { get; set; } public string Note { get; set; } = ""; public Guid ActorId { get; set; } }
public sealed class SaleReturn : Entity { public string InvoiceJson { get; set; } = "{}"; public Guid SaleId { get; set; } public string Number { get; set; } = ""; public string Reason { get; set; } = ""; public DateOnly BusinessDate { get; set; } public decimal Credit { get; set; } public bool Cancellation { get; set; } }
public sealed class SaleReturnItem : Entity { public decimal Taxable { get; set; } public decimal Cgst { get; set; } public decimal Sgst { get; set; } public decimal Igst { get; set; } public decimal Cess { get; set; } public Guid SaleReturnId { get; set; } public Guid SaleItemId { get; set; } public int Quantity { get; set; } public string Disposition { get; set; } = "Restock"; public decimal Credit { get; set; } public decimal Cost { get; set; } }
public sealed class StockTransfer : Entity { public Guid FromBranchId { get; set; } public Guid ToBranchId { get; set; } public string Number { get; set; } = ""; public string Status { get; set; } = "InTransit"; public string Note { get; set; } = ""; }
public sealed class StockTransferItem : Entity { public int ReceivedQuantity { get; set; } public Guid StockTransferId { get; set; } public Guid ProductVariantId { get; set; } public Guid? StockUnitId { get; set; } public Guid? StockCostLayerId { get; set; } public int Quantity { get; set; } public decimal UnitCost { get; set; } }
public sealed class Expense : Entity { public Guid BranchId { get; set; } public string Category { get; set; } = ""; public string Description { get; set; } = ""; public decimal Amount { get; set; } public PaymentMethod Method { get; set; } public DateOnly BusinessDate { get; set; } public Guid? ReversesExpenseId { get; set; } public Guid ActorId { get; set; } }
public sealed class DocumentSequence : Entity { public Guid BranchId { get; set; } public string Kind { get; set; } = ""; public int FinancialYear { get; set; } public int LastNumber { get; set; } }
public sealed class OperationReceipt : Entity { public string[] Permissions { get; set; } = []; public Guid[] BranchIds { get; set; } = []; public Guid UserId { get; set; } public string Key { get; set; } = ""; public string Operation { get; set; } = ""; public string RequestHash { get; set; } = ""; public string ResultJson { get; set; } = "{}"; }
public sealed class BusinessSettings : Entity { public int SingletonKey { get; set; } = 1; public string Json { get; set; } = "{}"; }
public sealed class DocumentFile : Entity { public Guid BranchId { get; set; } public string Name { get; set; } = ""; public string MimeType { get; set; } = ""; public string StorageKey { get; set; } = ""; public long Size { get; set; } public Guid? PurchaseId { get; set; } public Guid? ExpenseId { get; set; } }
public sealed class DeviceInspection : Entity { public string SellerName { get; set; } = ""; public string AadhaarLastFour { get; set; } = ""; public Guid StockUnitId { get; set; } public string Notes { get; set; } = ""; public int? BatteryHealth { get; set; } public string ChecksJson { get; set; } = "{}"; public int WarrantyDays { get; set; } }
public sealed class DeviceAcquisition : Entity { public Guid BranchId { get; set; } public Guid CustomerId { get; set; } public Guid StockUnitId { get; set; } public decimal Amount { get; set; } public Guid? ExchangeSaleId { get; set; } public Guid? PaymentId { get; set; } }

public sealed class SaleNonCashSettlement : Entity { public Guid SaleId { get; set; } public Guid DeviceAcquisitionId { get; set; } public decimal Amount { get; set; } }
public sealed class PurchaseReturn : Entity { public Guid PurchaseId { get; set; } public DateOnly BusinessDate { get; set; } public string SupplierCreditReference { get; set; } = ""; public string Reason { get; set; } = ""; public decimal Credit { get; set; } }
public sealed class PurchaseReturnItem : Entity { public Guid PurchaseReturnId { get; set; } public Guid PurchaseItemId { get; set; } public Guid? StockUnitId { get; set; } public int Quantity { get; set; } public decimal Credit { get; set; } }

public sealed class NonCashSettlementReversal : Entity { public Guid SaleNonCashSettlementId { get; set; } public decimal Amount { get; set; } public string Reason { get; set; } = ""; }

public sealed class ImportJob : Entity
{
    public Guid? BranchId { get; set; }
    public Guid ActorId { get; set; }
    public string Kind { get; set; } = "";
    public string RowsJson { get; set; } = "[]";
    public string ErrorsJson { get; set; } = "[]";
    public string Status { get; set; } = "Validated";
    public int RowCount { get; set; }
}

public sealed class PaymentFollowUp : Entity { public Guid BranchId { get; set; } public Guid CustomerId { get; set; } public Guid ActorId { get; set; } public string Kind { get; set; } = ""; public string Note { get; set; } = ""; public DateOnly? PromiseDate { get; set; } public DateOnly? NextContactDate { get; set; } public decimal? Amount { get; set; } }
