using Invora.Contracts.Retail;
using Invora.Domain.Common;
using Invora.Domain.Modules.Retail;
using Invora.Infrastructure.Modules.Catalog;
using Invora.Infrastructure.Modules.Inventory;
using Invora.Infrastructure.Modules.Retail;
using Microsoft.EntityFrameworkCore;
namespace Invora.Infrastructure.Modules.StockTransfers;
public sealed class TransferService(RetailOperations r,CatalogService catalog,StockService stock)
{
    public Task<DocumentView> DispatchAsync(TransferRequest request,string key,CancellationToken ct)=>r.ExecuteAsync("transfer-dispatch",key,request,async()=>{
        await r.BranchAsync(request.FromBranchId,"inventory.transfer",ct);await r.BranchAsync(request.ToBranchId,"inventory.transfer",ct);RetailOperations.Check(request.FromBranchId!=request.ToBranchId && request.Items is {Length:>0 and <=200},"Transfer needs different branches and item lines.");
        var transfer=new StockTransfer{FromBranchId=request.FromBranchId,ToBranchId=request.ToBranchId,Note=request.Note??"",Number=await r.NumberAsync(request.FromBranchId,"TRF",await r.TodayAsync(ct),ct)};r.Db.Add(transfer);
        foreach(var line in request.Items)
        {
            var p=await catalog.ProductAsync(line.ProductVariantId,ct);RetailOperations.Check(line.Quantity>0,"Quantity must be positive.");
            if(p.Variant.Serialized){RetailOperations.Check(line.Quantity==1 && line.StockUnitId!=null,"Choose one device per transfer line.");var unit=await r.Db.Set<StockUnit>().SingleOrDefaultAsync(x=>x.Id==line.StockUnitId && x.BranchId==request.FromBranchId && x.ProductVariantId==p.Variant.Id,ct)??throw new DomainException("NOT_FOUND","Device not found.");RetailOperations.Check(unit.Status==DeviceStatus.InStock,"Device unavailable.","INVENTORY_UNAVAILABLE");unit.Status=DeviceStatus.InTransit;r.Db.Add(new StockTransferItem{StockTransferId=transfer.Id,ProductVariantId=p.Variant.Id,StockUnitId=unit.Id,Quantity=1,UnitCost=unit.Cost});r.Movement(request.FromBranchId,p.Variant.Id,-1,"TransferOut",unit.Id,transfer:transfer.Id);}
            else{RetailOperations.Check(line.StockUnitId==null,"Quantity line cannot reference a device.");foreach(var layer in await stock.ConsumeAsync(request.FromBranchId,p.Variant.Id,line.Quantity,ct))r.Db.Add(new StockTransferItem{StockTransferId=transfer.Id,ProductVariantId=p.Variant.Id,StockCostLayerId=layer.Layer.Id,Quantity=layer.Quantity,UnitCost=layer.Layer.UnitCost});r.Movement(request.FromBranchId,p.Variant.Id,-line.Quantity,"TransferOut",transfer:transfer.Id);}
        }
        r.Audit("TRANSFER_DISPATCHED",transfer.Id,new{transfer.Number,transfer.FromBranchId,transfer.ToBranchId});return new DocumentView(transfer.Id,transfer.Number,transfer.Status,0);
    },ct);
    public Task<DocumentView> ReceiveAsync(Guid id,string key,CancellationToken ct)=>ReceiveItemsAsync(id,new(),key,ct);
    public Task<DocumentView> ReceiveItemsAsync(Guid id,TransferReceiptRequest request,string key,CancellationToken ct)=>r.ExecuteAsync("transfer-receive",key,new{id,request},async()=>{
        var transfer=await r.Db.Set<StockTransfer>().SingleOrDefaultAsync(x=>x.Id==id,ct)??throw new DomainException("NOT_FOUND","Transfer not found.");await r.BranchAsync(transfer.ToBranchId,"inventory.transfer",ct);RetailOperations.Check(transfer.Status is "InTransit" or "PartiallyReceived","Transfer already received or cancelled.");var items=await r.Db.Set<StockTransferItem>().Where(x=>x.StockTransferId==id).ToListAsync(ct);
        var receipts=request.Items??items.Where(x=>x.Quantity>x.ReceivedQuantity).Select(x=>new TransferReceiptLine(x.Id,x.Quantity-x.ReceivedQuantity)).ToArray();RetailOperations.Check(receipts.Length is >0 and <=200 && receipts.Select(x=>x.ItemId).Distinct().Count()==receipts.Length,"Receipt needs unique item lines.");
        foreach(var receipt in receipts){var line=items.SingleOrDefault(x=>x.Id==receipt.ItemId)??throw new DomainException("NOT_FOUND","Transfer item not found.");RetailOperations.Check(receipt.Quantity>0 && receipt.Quantity<=line.Quantity-line.ReceivedQuantity,"Receipt exceeds quantity in transit.");
            if(line.StockUnitId is Guid unitId){var unit=await r.Db.Set<StockUnit>().SingleAsync(x=>x.Id==unitId,ct);RetailOperations.Check(unit.Status==DeviceStatus.InTransit && receipt.Quantity==1,"Transfer device is unavailable.");unit.BranchId=transfer.ToBranchId;unit.Status=DeviceStatus.InStock;}
            else{var balance=await stock.BalanceAsync(transfer.ToBranchId,line.ProductVariantId,ct);balance.Quantity+=receipt.Quantity;r.Db.Add(new StockCostLayer{BranchId=transfer.ToBranchId,ProductVariantId=line.ProductVariantId,ReceivedQuantity=receipt.Quantity,RemainingQuantity=receipt.Quantity,UnitCost=line.UnitCost,OriginLayerId=line.StockCostLayerId});}
            line.ReceivedQuantity+=receipt.Quantity;r.Movement(transfer.ToBranchId,line.ProductVariantId,receipt.Quantity,"TransferIn",line.StockUnitId,transfer:id);
        }
        transfer.Status=items.All(x=>x.Quantity==x.ReceivedQuantity)?"Completed":"PartiallyReceived";r.Audit("TRANSFER_RECEIVED",id,request);return new DocumentView(id,transfer.Number,transfer.Status,0);
    },ct);
    public async Task<object> DetailAsync(Guid id,CancellationToken ct){var transfer=await r.Db.Set<StockTransfer>().AsNoTracking().SingleOrDefaultAsync(x=>x.Id==id,ct)??throw new DomainException("NOT_FOUND","Transfer not found.");var branch=await r.Db.StaffBranches.Where(x=>x.UserId==r.Actor && (x.BranchId==transfer.FromBranchId||x.BranchId==transfer.ToBranchId)).Select(x=>x.BranchId).FirstOrDefaultAsync(ct);await r.BranchAsync(branch,"inventory.transfer",ct);var lines=new List<object>();foreach(var line in await r.Db.Set<StockTransferItem>().Where(x=>x.StockTransferId==id).ToArrayAsync(ct)){var p=await catalog.ProductAsync(line.ProductVariantId,ct);lines.Add(new{line.Id,line.Quantity,line.ReceivedQuantity,description=CatalogService.Description(p.Model,p.Variant),identifiers=line.StockUnitId is Guid unit?await r.Db.Set<UnitIdentifier>().Where(x=>x.StockUnitId==unit).Select(x=>x.Value).ToArrayAsync(ct):[]});}return new{transfer.Id,transfer.Number,transfer.Status,transfer.FromBranchId,transfer.ToBranchId,transfer.Note,items=lines};}
    public Task<DocumentView> CancelAsync(Guid id,ReasonRequest request,string key,CancellationToken ct)=>r.ExecuteAsync("transfer-cancel",key,new{id,request},async()=>{
        var transfer=await r.Db.Set<StockTransfer>().SingleOrDefaultAsync(x=>x.Id==id,ct)??throw new DomainException("NOT_FOUND","Transfer not found.");await r.BranchAsync(transfer.FromBranchId,"inventory.transfer",ct);await r.BranchAsync(transfer.ToBranchId,"inventory.transfer",ct);RetailOperations.Text(request.Reason,"Reason");RetailOperations.Check(transfer.Status is "InTransit" or "PartiallyReceived","Received stock must be transferred back through a new transfer.");
        foreach(var item in await r.Db.Set<StockTransferItem>().Where(x=>x.StockTransferId==id).ToListAsync(ct)){var remaining=item.Quantity-item.ReceivedQuantity;if(remaining==0)continue;if(item.StockUnitId is Guid unitId){var unit=await r.Db.Set<StockUnit>().SingleAsync(x=>x.Id==unitId,ct);RetailOperations.Check(unit.Status==DeviceStatus.InTransit,"Invalid transfer state.");unit.Status=DeviceStatus.InStock;}else{var layer=await r.Db.Set<StockCostLayer>().SingleAsync(x=>x.Id==item.StockCostLayerId,ct);layer.RemainingQuantity+=remaining;(await stock.BalanceAsync(transfer.FromBranchId,item.ProductVariantId,ct)).Quantity+=remaining;}r.Movement(transfer.FromBranchId,item.ProductVariantId,remaining,"TransferCancelled",item.StockUnitId,transfer:id,note:request.Reason);}
        transfer.Status=transfer.Status=="PartiallyReceived"?"PartiallyCancelled":"Cancelled";r.Audit("TRANSFER_CANCELLED",id,request);return new DocumentView(id,transfer.Number,transfer.Status,0);
    },ct);
    public async Task<object> ListAsync(Guid branch,CancellationToken ct){await r.BranchAsync(branch,"inventory.view",ct);return await r.Db.Set<StockTransfer>().AsNoTracking().Where(x=>x.FromBranchId==branch || x.ToBranchId==branch).OrderByDescending(x=>x.CreatedAtUtc).Take(100).Select(x=>new{x.Id,x.Number,x.Status,x.FromBranchId,x.ToBranchId,x.Note}).ToArrayAsync(ct);}
}
