import {Component,inject,signal} from '@angular/core';import {FormBuilder,ReactiveFormsModule,Validators} from '@angular/forms';import {Router,RouterLink} from '@angular/router';import {AuthService} from '../../core/auth';import {BranchContext,errorText} from '../../core/api';
@Component({standalone:true,imports:[ReactiveFormsModule,RouterLink],template:`<main class="auth-layout"><section class="auth-story"><a class="brand" routerLink="/">invora<span>●</span></a><div><p class="eyebrow">THE RETAIL WORKSPACE</p><h1>A clear view of<br>your business.</h1><p>Every device. Every sale.<br>Every rupee, accounted for.</p><div class="story-line"></div><small>Inventory. Billing. Business. Simplified.</small></div><small>Built for the rhythm of your store.</small></section><section class="auth-form"><div class="auth-card"><p class="eyebrow">{{setup?'YOUR FIRST BRANCH':'WELCOME BACK'}}</p><h2>{{setup?'Set up your business':'Open your workspace'}}</h2><p class="muted">{{setup?'Create the business and its owner account.':'Sign in with your staff account to begin.'}}</p><form [formGroup]="form" (ngSubmit)="submit()">@if(setup){<label>Business name<input formControlName="tradeName" autocomplete="organization" maxlength="200" required></label><div class="form-grid"><label>Branch code<input formControlName="branchCode" maxlength="20"></label><label>Branch name<input formControlName="branchName" maxlength="200" required></label></div><label>Owner name<input formControlName="ownerName" autocomplete="name" maxlength="200" required></label><label>Setup key<input formControlName="bootstrap" type="password" autocomplete="off" required></label>}<label>{{setup?'Owner login':'Login'}}<input formControlName="login" autocomplete="username" maxlength="100" required></label><label>Password<input type="password" formControlName="password" autocomplete="{{setup?'new-password':'current-password'}}" required maxlength="128" [attr.minlength]="setup?12:null"></label>@if(setup){<p class="small muted">Password must contain 12–128 characters. Fill in every setup field.</p>}@if(form.invalid && form.touched){<p class="error" role="alert">{{validationMessage()}}</p>}<p role="alert" class="error">{{error()}}</p><button class="primary wide" [disabled]="busy()||form.invalid">{{busy()?'Opening…':setup?'Create workspace':'Sign in →'}}</button></form><p class="small muted">{{setup?'Already set up?':'Opening a new store?'}} <a [routerLink]="setup?'/login':'/setup'">{{setup?'Sign in':'Set up Invora'}}</a></p></div></section></main>`})
export class AuthPage {
 private fb=inject(FormBuilder);private router=inject(Router);private auth=inject(AuthService);private branches=inject(BranchContext);setup=this.router.url.startsWith('/setup');readonly busy=signal(false);readonly error=signal('');
 readonly form=this.fb.nonNullable.group({login:['',[Validators.required]],password:['',[Validators.required]],tradeName:[''],branchCode:['MAIN'],branchName:['Main branch'],ownerName:[''],bootstrap:['']});
 constructor(){this.form.controls.login.addValidators(Validators.maxLength(100));if(this.setup){this.form.controls.password.addValidators([Validators.minLength(12),Validators.maxLength(128)]);for(const name of ['tradeName','branchCode','branchName','ownerName','bootstrap'] as const)this.form.controls[name].addValidators(Validators.required);this.form.controls.tradeName.addValidators(Validators.maxLength(200));this.form.controls.branchCode.addValidators(Validators.maxLength(20));this.form.controls.branchName.addValidators(Validators.maxLength(200));this.form.controls.ownerName.addValidators(Validators.maxLength(200));}for(const control of Object.values(this.form.controls))control.updateValueAndValidity();}
 validationMessage(){const labels:Record<string,string>={login:this.setup?'Owner login':'Login',password:'Password',tradeName:'Business name',branchCode:'Branch code',branchName:'Branch name',ownerName:'Owner name',bootstrap:'Setup key'};return Object.entries(this.form.controls).filter(([,c])=>c.invalid && (c.touched||c.dirty)).map(([name,c])=>c.hasError('required')?labels[name]+' is required.':c.hasError('minlength')?'Password must contain at least 12 characters.':labels[name]+' is too long.').join(' ');}
 async submit(){if(this.form.invalid||this.busy())return;this.busy.set(true);this.error.set('');try{const v=this.form.getRawValue();if(this.setup)await this.auth.setup({tradeName:v.tradeName,branchCode:v.branchCode,branchName:v.branchName,ownerLogin:v.login,ownerName:v.ownerName,password:v.password},v.bootstrap);else await this.auth.login(v.login,v.password);this.form.controls.password.setValue('');this.form.controls.bootstrap.setValue('');await this.branches.load();await this.router.navigateByUrl('/');}catch(e){this.error.set(errorText(e));}finally{this.busy.set(false);}}
}
