using Invora.Contracts.Common;
using Invora.Contracts.Retail;
using Invora.Domain.Common;
using Invora.Domain.Modules.Retail;
using Invora.Infrastructure.Modules.Retail;
using Microsoft.EntityFrameworkCore;
namespace Invora.Infrastructure.Modules.Catalog;
public sealed class CatalogService(RetailOperations r)
{
    public static bool IsMobile(string category)=>new[]{"Mobile","Smartphone","Mobile phone","Phone"}.Contains(category.Trim(),StringComparer.OrdinalIgnoreCase);
    public async Task<bool> RequiresImeiAsync(string category,CancellationToken ct)=>IsMobile(category)||await r.Db.Set<ProductCategory>().AnyAsync(x=>x.NormalizedName==category.Trim().ToUpperInvariant()&&x.RequiresImei,ct);
    public async Task<CategoryView[]> CategoriesAsync(CancellationToken ct){await r.PermissionAsync("inventory.view",ct);var rows=await r.Db.Set<ProductCategory>().OrderBy(x=>x.Name).Select(x=>new CategoryView(x.Name,x.RequiresImei)).ToArrayAsync(ct);var existing=await r.Db.Set<ProductModel>().Select(x=>x.Category).Distinct().ToArrayAsync(ct);return rows.Concat(existing.Where(name=>!rows.Any(x=>x.Name.Equals(name,StringComparison.OrdinalIgnoreCase))).Select(name=>new CategoryView(name,IsMobile(name)))).OrderBy(x=>x.Name,StringComparer.OrdinalIgnoreCase).ToArray();}
    public Task<CategoryView> CreateCategoryAsync(CategoryRequest request,string key,CancellationToken ct)=>r.ExecuteAsync("category-create",key,request,async()=>{await r.PermissionAsync("inventory.create",ct);RetailOperations.Text(request.Name,"Category",100);var name=request.Name.Trim();var normalized=name.ToUpperInvariant();var existing=await r.Db.Set<ProductCategory>().SingleOrDefaultAsync(x=>x.NormalizedName==normalized,ct);if(existing is not null){RetailOperations.Check(existing.RequiresImei==(request.RequiresImei||IsMobile(name)),"Category already exists with a different stock type. Use that category or choose another name.","CATEGORY_EXISTS");return new CategoryView(existing.Name,existing.RequiresImei);}var category=new ProductCategory{Name=name,NormalizedName=normalized,RequiresImei=request.RequiresImei||IsMobile(name)};r.Db.Add(category);r.Audit("CATEGORY_CREATED",category.Id,request);return new CategoryView(name,category.RequiresImei);},ct);
    public async Task<string[]> BrandsAsync(CancellationToken ct){await r.PermissionAsync("inventory.view",ct);var names=await r.Db.Set<Brand>().Select(x=>x.Name).ToArrayAsync(ct);var existing=await r.Db.Set<ProductModel>().Select(x=>x.Brand).Distinct().ToArrayAsync(ct);return names.Concat(existing).Distinct(StringComparer.OrdinalIgnoreCase).OrderBy(x=>x,StringComparer.OrdinalIgnoreCase).ToArray();}
    public Task<string> CreateBrandAsync(BrandRequest request,string key,CancellationToken ct)=>r.ExecuteAsync("brand-create",key,request,async()=>{await r.PermissionAsync("inventory.create",ct);RetailOperations.Text(request.Name,"Brand",100);var name=request.Name.Trim();var normalized=name.ToUpperInvariant();var existing=await r.Db.Set<Brand>().SingleOrDefaultAsync(x=>x.NormalizedName==normalized,ct);if(existing is not null)return existing.Name;var brand=new Brand{Name=name,NormalizedName=normalized};r.Db.Add(brand);r.Audit("BRAND_CREATED",brand.Id,request);return name;},ct);
    public async Task<object> TaxRatesAsync(CancellationToken ct){await r.PermissionAsync("inventory.view",ct);return await r.Db.Set<TaxRate>().AsNoTracking().OrderBy(x=>x.Rate).Select(x=>new{x.Id,x.Name,x.Rate,x.CessRate,x.IsActive}).ToArrayAsync(ct);}
    public Task<Guid> CreateTaxAsync(TaxRequest request,string key,CancellationToken ct)=>r.ExecuteAsync("tax-create",key,request,async()=>{
        await r.PermissionAsync("business.settings",ct);RetailOperations.Text(request.Name,"Tax name",100);RetailOperations.Check(request.Rate is >=0 and <=100 && request.CessRate is >=0 and <=100 && decimal.Round(request.Rate,4)==request.Rate && decimal.Round(request.CessRate,4)==request.CessRate,"Tax rates must be 0–100 with at most four decimal places.");
        var existing=await r.Db.Set<TaxRate>().FirstOrDefaultAsync(x=>x.IsActive && x.Rate==request.Rate && x.CessRate==request.CessRate,ct);if(existing is not null)return existing.Id;
        var tax=new TaxRate{Name=request.Name.Trim(),Rate=request.Rate,CessRate=request.CessRate};r.Db.Add(tax);r.Audit("TAX_CREATED",tax.Id,request);return tax.Id;
    },ct);
    public async Task<PageResponse<ProductView>> ProductsAsync(int page,int size,string? search,CancellationToken ct,string? category=null,string? brand=null)
    {
        await r.PermissionAsync("inventory.view",ct);RetailOperations.Page(page,size);
        var query=from v in r.Db.Set<ProductVariant>().AsNoTracking() join m in r.Db.Set<ProductModel>() on v.ProductModelId equals m.Id join t in r.Db.Set<TaxRate>() on m.TaxRateId equals t.Id where v.IsActive select new{v,m,t};
        var parts=RetailOperations.SearchParts(search);
        foreach(var term in parts.Terms){var compact=term.Replace(" ","");query=query.Where(x=>(x.m.Brand+" "+x.m.Name+" "+x.m.Category+" "+x.v.Ram+" "+x.v.Storage+" "+x.v.Color+" "+x.v.Sku+" "+(x.v.Barcode??"")).ToUpper().Replace(" ","").Contains(compact)||r.Db.Set<UnitIdentifier>().Any(i=>i.Value.Contains(compact)&&r.Db.Set<StockUnit>().Any(u=>u.Id==i.StockUnitId&&u.ProductVariantId==x.v.Id&&r.Db.StaffBranches.Any(b=>b.UserId==r.Actor&&b.BranchId==u.BranchId))));}
        if(parts.Ram is not null)query=query.Where(x=>x.v.Ram.ToUpper().Replace(" ","").Replace("GB","")==parts.Ram&&x.v.Storage.ToUpper().Replace(" ","").Replace("GB","")==parts.Storage);
        if(!string.IsNullOrWhiteSpace(category)){var selected=category.Trim().ToUpperInvariant();query=IsMobile(selected)?query.Where(x=>new[]{"MOBILE","SMARTPHONE","MOBILE PHONE","PHONE"}.Contains(x.m.Category.ToUpper())||r.Db.Set<ProductCategory>().Any(c=>c.RequiresImei&&c.NormalizedName==x.m.Category.ToUpper())):query.Where(x=>x.m.Category.ToUpper()==selected);}
        if(!string.IsNullOrWhiteSpace(brand)){var selected=brand.Trim().ToUpperInvariant();query=query.Where(x=>x.m.Brand.ToUpper()==selected);}
        var total=await query.LongCountAsync(ct);var rows=await query.OrderBy(x=>x.m.Name).ThenBy(x=>x.v.Id).Skip((page-1)*size).Take(size).ToArrayAsync(ct);
        var mobileNames=await r.Db.Set<ProductCategory>().Where(x=>x.RequiresImei).Select(x=>x.NormalizedName).ToArrayAsync(ct);
        return new(rows.Select(x=>new ProductView(x.v.Id,x.m.Name,x.m.Brand,x.m.Category,x.m.Hsn,x.v.Sku,x.v.Barcode,x.v.Ram,x.v.Storage,x.v.Color,x.v.Serialized,x.v.SellingPrice,x.v.Mrp,x.t.Id,x.t.Rate,x.t.CessRate,x.m.WarrantyMonths,x.m.Id,IsMobile(x.m.Category)||mobileNames.Contains(x.m.Category.ToUpperInvariant()))).ToArray(),page,size,total);
    }
    public Task<Guid> CreateProductAsync(ProductRequest request,string key,CancellationToken ct)=>r.ExecuteAsync("product-create",key,request,()=>CreateInternalAsync(request,ct),ct);
    public async Task<Guid> CreateInternalAsync(ProductRequest request,CancellationToken ct){
        await r.PermissionAsync("inventory.create",ct);RetailOperations.Text(request.Name,"Product name",200);RetailOperations.Text(request.Brand,"Brand",100);RetailOperations.Text(request.Category,"Category",100);RetailOperations.Text(request.Hsn,"HSN",20);RetailOperations.Text(request.Sku,"SKU",100);
        RetailOperations.Money(request.SellingPrice);RetailOperations.Money(request.Mrp);RetailOperations.Check(request.WarrantyMonths is >=0 and <=120,"Invalid warranty.");
        RetailOperations.Check(await r.Db.Set<TaxRate>().AnyAsync(x=>x.Id==request.TaxRateId && x.IsActive,ct),"Tax not found.","NOT_FOUND");
        var sku=request.Sku.Trim().ToUpperInvariant();var barcode=string.IsNullOrWhiteSpace(request.Barcode)?null:request.Barcode.Trim();RetailOperations.Check(!r.Db.Set<ProductVariant>().Local.Any(x=>x.Sku==sku || barcode!=null && x.Barcode==barcode) && !await r.Db.Set<ProductVariant>().AnyAsync(x=>x.Sku==sku || barcode!=null && x.Barcode==barcode,ct),"SKU or barcode already exists.","PRODUCT_EXISTS");
        RetailOperations.Check(!await RequiresImeiAsync(request.Category,ct)||request.Serialized,"Mobile phones must be tracked individually by IMEI.");ValidateSpecs(request.Ram,request.Storage,request.Color);
        ProductModel model;
        if(request.ProductModelId is Guid modelId){model=await r.Db.Set<ProductModel>().SingleOrDefaultAsync(x=>x.Id==modelId,ct)??throw new DomainException("NOT_FOUND","Product model not found.");RetailOperations.Check(model.Name==request.Name.Trim()&&model.Brand==request.Brand.Trim()&&model.Category==request.Category.Trim()&&model.Hsn==request.Hsn.Trim()&&model.TaxRateId==request.TaxRateId&&model.WarrantyMonths==request.WarrantyMonths,"A new variant must retain its model's name, brand, category, HSN, tax and warranty.");}
        else{model=new ProductModel{Name=request.Name.Trim(),Brand=request.Brand.Trim(),Category=request.Category.Trim(),Hsn=request.Hsn.Trim(),TaxRateId=request.TaxRateId,WarrantyMonths=request.WarrantyMonths};r.Db.Add(model);}

        var variant=new ProductVariant{ProductModelId=model.Id,Sku=sku,Barcode=barcode,Ram=request.Ram??"",Storage=request.Storage??"",Color=request.Color??"",Serialized=request.Serialized,SellingPrice=request.SellingPrice,Mrp=request.Mrp};r.Db.Add(variant);r.Audit("PRODUCT_CREATED",variant.Id,request);return variant.Id;
    }
    public static ProductRequest SeedDeviceProduct(ProductRequest product,DeviceStockLine[]? rows)
    {
        if(rows is null or {Length:0})return product;
        RetailOperations.Check(rows.All(x=>x is not null&&x.Device is not null),"Each device row needs identity and specifications.");
        if(!product.Serialized)return product;var first=rows[0];return product with{Ram=first.Ram,Storage=first.Storage,Color=first.Color,SellingPrice=first.SellingPrice,Mrp=first.Mrp};
    }
    public Task<PreparedPurchaseLine[]> PreparePurchaseAsync(ProductPurchaseRequest request,string key,CancellationToken ct)=>r.ExecuteAsync("purchase-product-prepare",key,request,async()=>{
        await r.PermissionAsync("purchase.create",ct);RetailOperations.Check(request.Quantity is >0 and <=100000,"Enter a whole purchase quantity.");RetailOperations.Money(request.UnitCost);
        var id=await CreateInternalAsync(SeedDeviceProduct(request.Product,request.DeviceStock),ct);await r.Db.SaveChangesAsync(ct);var (basis,model,tax)=await ProductAsync(id,ct);
        if(!basis.Serialized){RetailOperations.Check(request.DeviceStock is null or {Length:0},"Quantity products cannot have device identities.");return new[]{new PreparedPurchaseLine(await ViewAsync(id,ct),request.Quantity,request.UnitCost,[])};}
        RetailOperations.Check(request.DeviceStock is {Length:>0 and <=100}&&request.DeviceStock.Length==request.Quantity,"Enter one device row for every phone or device.");var seen=new HashSet<string>();var prepared=new List<(Guid Id,decimal Cost,DeviceCapture Device)>();var mobile=await RequiresImeiAsync(model.Category,ct);
        foreach(var row in request.DeviceStock!){var ids=Invora.Infrastructure.Modules.Inventory.StockService.Normalize(row.Device);RetailOperations.Check(!mobile||ids.Any(i=>i.Kind=="IMEI"),"Every phone needs its IMEI.");foreach(var identity in ids){RetailOperations.Check(seen.Add(identity.Kind+":"+identity.Value),"A device identity is repeated.");RetailOperations.Check(!await r.Db.Set<UnitIdentifier>().AnyAsync(i=>i.Kind==identity.Kind&&i.Value==identity.Value,ct),"This IMEI or serial already exists in inventory.","IDENTIFIER_EXISTS");}var variant=await DeviceVariantAsync(basis,model,row,ct);prepared.Add((variant.Id,row.UnitCost,row.Device));}
        await r.Db.SaveChangesAsync(ct);var lines=new List<PreparedPurchaseLine>();foreach(var group in prepared.GroupBy(x=>new{x.Id,x.Cost}))lines.Add(new(await ViewAsync(group.Key.Id,ct),group.Count(),group.Key.Cost,group.Select(x=>x.Device).ToArray()));r.Audit("PURCHASE_PRODUCT_PREPARED",id,new{request.Quantity,variantCount=lines.Count});return lines.ToArray();
    },ct);
    public Task<Guid> UpdateAsync(Guid id,ProductRequest request,string key,CancellationToken ct)=>r.ExecuteAsync("product-update",key,new{id,request},async()=>{
        await r.PermissionAsync("inventory.create",ct);var p=await ProductAsync(id,ct);RetailOperations.Check(!await RequiresImeiAsync(request.Category,ct)||request.Serialized,"Mobile phones must be tracked individually by IMEI.");ValidateSpecs(request.Ram,request.Storage,request.Color);RetailOperations.Text(request.Name,"Name",200);RetailOperations.Text(request.Brand,"Brand",100);RetailOperations.Text(request.Category,"Category",100);RetailOperations.Text(request.Hsn,"HSN",20);RetailOperations.Money(request.SellingPrice);RetailOperations.Money(request.Mrp);RetailOperations.Check(request.WarrantyMonths is >=0 and <=120,"Invalid warranty.");RetailOperations.Check(request.Serialized==p.Variant.Serialized && request.Sku.Trim().ToUpperInvariant()==p.Variant.Sku,"Inventory type and SKU cannot change after creation.");RetailOperations.Check(await r.Db.Set<TaxRate>().AnyAsync(x=>x.Id==request.TaxRateId && x.IsActive,ct),"Tax not found.","NOT_FOUND");var barcode=string.IsNullOrWhiteSpace(request.Barcode)?null:request.Barcode.Trim();RetailOperations.Check(barcode==null || !await r.Db.Set<ProductVariant>().AnyAsync(x=>x.Id!=id && x.Barcode==barcode,ct),"Barcode already exists.");var before=new{p.Model.Name,p.Model.Brand,p.Model.TaxRateId,p.Variant.SellingPrice,p.Variant.Mrp};
        p.Model.Name=request.Name.Trim();p.Model.Brand=request.Brand.Trim();p.Model.Category=request.Category.Trim();p.Model.Hsn=request.Hsn.Trim();p.Model.TaxRateId=request.TaxRateId;p.Model.WarrantyMonths=request.WarrantyMonths;p.Variant.Barcode=barcode;var changedSpecs=p.Variant.Ram!=(request.Ram??"")||p.Variant.Storage!=(request.Storage??"")||p.Variant.Color!=(request.Color??"");RetailOperations.Check(!changedSpecs||!await r.Db.Set<StockUnit>().AnyAsync(x=>x.ProductVariantId==id,ct),"Use Inventory → Edit device to correct a received phone. Add a variant for a different configuration.");p.Variant.Ram=request.Ram??"";p.Variant.Storage=request.Storage??"";p.Variant.Color=request.Color??"";p.Variant.SellingPrice=request.SellingPrice;p.Variant.Mrp=request.Mrp;r.Audit("PRODUCT_UPDATED",id,new{before,after=request});return id;
    },ct);
    public async Task<(ProductVariant Variant,ProductModel Model,TaxRate Tax)> ProductAsync(Guid id,CancellationToken ct)
    {
        var v=await r.Db.Set<ProductVariant>().SingleOrDefaultAsync(x=>x.Id==id && x.IsActive,ct)??throw new DomainException("NOT_FOUND","Product not found.");
        var m=await r.Db.Set<ProductModel>().SingleAsync(x=>x.Id==v.ProductModelId,ct);var t=await r.Db.Set<TaxRate>().SingleAsync(x=>x.Id==m.TaxRateId,ct);return(v,m,t);
    }
    public async Task<ProductView> ViewAsync(Guid id,CancellationToken ct){await r.PermissionAsync("inventory.view",ct);var (v,m,t)=await ProductAsync(id,ct);return new(v.Id,m.Name,m.Brand,m.Category,m.Hsn,v.Sku,v.Barcode,v.Ram,v.Storage,v.Color,v.Serialized,v.SellingPrice,v.Mrp,t.Id,t.Rate,t.CessRate,m.WarrantyMonths,m.Id,await RequiresImeiAsync(m.Category,ct));}
    private static string Spec(string? value)=>(value??"").Trim().ToUpperInvariant().Replace(" ","");
    private static void ValidateSpecs(string? ram,string? storage,string? color){RetailOperations.Check((ram?.Length??0)<=50 && (storage?.Length??0)<=50 && (color?.Length??0)<=100,"Memory or color is too long.");}
    public async Task<ProductVariant> DeviceVariantAsync(ProductVariant basis,ProductModel model,DeviceStockLine device,CancellationToken ct,bool correction=false){
        RetailOperations.Check(basis.Serialized,"Device rows require individually tracked stock.");ValidateSpecs(device.Ram,device.Storage,device.Color);RetailOperations.Money(device.UnitCost);RetailOperations.Money(device.SellingPrice);RetailOperations.Money(device.Mrp);
        var candidates=r.Db.Set<ProductVariant>().Local.Where(x=>x.ProductModelId==model.Id&&x.Serialized&&x.IsActive).Concat(await r.Db.Set<ProductVariant>().Where(x=>x.ProductModelId==model.Id&&x.Serialized&&x.IsActive).ToArrayAsync(ct));
        var found=candidates.FirstOrDefault(x=>Spec(x.Ram)==Spec(device.Ram)&&Spec(x.Storage)==Spec(device.Storage)&&Spec(x.Color)==Spec(device.Color)&&x.SellingPrice==device.SellingPrice&&x.Mrp==device.Mrp);if(found is not null)return found;
        await r.PermissionAsync(correction?"inventory.adjust":"inventory.create",ct);var variant=new ProductVariant{ProductModelId=model.Id,Sku="ITEM-"+Guid.NewGuid().ToString("N")[..12].ToUpperInvariant(),Ram=(device.Ram??"").Trim(),Storage=(device.Storage??"").Trim(),Color=(device.Color??"").Trim(),Serialized=true,SellingPrice=device.SellingPrice,Mrp=device.Mrp};r.Db.Add(variant);r.Audit("PRODUCT_VARIANT_CREATED",variant.Id,new{model.Id,variant.Ram,variant.Storage,variant.Color,variant.SellingPrice});return variant;
    }
    public static string Description(ProductModel m,ProductVariant v)=>string.Join(" ",new[]{m.Brand,m.Name,v.Ram,v.Storage,v.Color}.Where(x=>!string.IsNullOrWhiteSpace(x)));
}
