<Project Sdk="Microsoft.NET.Sdk.Web"><ItemGroup><ProjectReference Include="../Invora.Application/Invora.Application.csproj" /><ProjectReference Include="../Invora.Infrastructure/Invora.Infrastructure.csproj" /><ProjectReference Include="../Invora.Contracts/Invora.Contracts.csproj" /><PackageReference Include="Serilog.AspNetCore" /><PackageReference Include="Swashbuckle.AspNetCore" /><PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" /></ItemGroup></Project>