import {Component,effect,inject,input,output,signal,untracked} from '@angular/core';
import {CurrencyPipe,DatePipe} from '@angular/common';
import {FormBuilder,FormControl,ReactiveFormsModule,Validators} from '@angular/forms';
import {ApiService,BranchContext,errorText} from '../../core/api';
import {AuthService} from '../../core/auth';
import {Page,Row} from '../../core/models';
@Component({selector:'invora-customer-followup',standalone:true,imports:[CurrencyPipe,DatePipe,ReactiveFormsModule],template:`
<div class="followup-contact"><label>Contact number<select [formControl]="phone">@for(number of phones();track number){<option [value]="number">{{number}}</option>}</select></label><div class="contact-actions"><a class="secondary" [href]="'tel:'+dialNumber()">Call customer</a>@if(shop()){<a class="secondary" [href]="smsLink()">SMS draft</a><a class="primary" [href]="whatsappLink()" target="_blank" rel="noopener noreferrer">WhatsApp draft ↗</a>}@else{<span class="small muted" role="status">Loading reminder details…</span>}</div></div>
<label>Reminder message<textarea [formControl]="reminder" rows="15" maxlength="2000"></textarea></label>@if(shop()&&!shop()!.phone){<p class="panel-note">Add the shop contact number in Business settings so customers can call you back.</p>}<p class="small muted">Opens a draft for you to review and send. Record the outcome below after speaking to the customer.</p><button type="button" class="text-link" (click)="copyMessage()">Copy reminder message</button><button type="button" class="text-link" (click)="resetMessage()">Use latest promise message</button>
@if(auth.can('reports.export')){<div class="statement-actions"><div class="form-grid"><label>Statement from<input type="date" [formControl]="from"></label><label>Statement to<input type="date" [formControl]="to"></label></div><div class="contact-actions"><button type="button" class="secondary" [disabled]="busy()" (click)="statement(false)">Download customer statement PDF</button><button type="button" class="secondary" [disabled]="busy()" (click)="statement(true)">Share statement…</button></div><small class="muted">The PDF includes sales, payments and independent LenDen with running balances. Attach it to your WhatsApp conversation.</small></div>}
@if(auth.can('customers.manage')){<section class="counter-section"><h3>Payment promise / follow-up</h3><fieldset [formGroup]="form" class="plain-fieldset" [disabled]="busy()"><label>Follow-up type<select formControlName="kind"><option value="Promise">Customer promised payment</option><option value="Reminder">Reminder sent</option><option value="Call">Called customer</option><option value="Note">Conversation note</option><option value="ClearPromise">Close / clear previous promise</option></select></label><div class="form-grid">@if(form.controls.kind.value==='Promise'){<label>Promised payment date<input type="date" formControlName="promiseDate" required></label><label>Promised amount (optional)<input type="number" min="0.01" step="0.01" formControlName="amount"></label>}<label>Next reminder / call date<input type="date" formControlName="nextContactDate"></label></div><label>Conversation / reminder note<textarea formControlName="note" rows="3" maxlength="2000" placeholder="What did the customer say? Which payment is expected?" required></textarea></label><button type="button" class="primary" [disabled]="busy()||form.invalid||(form.controls.kind.value==='Promise'&&!form.controls.promiseDate.value)" (click)="save()">{{busy()?'Saving…':'Save follow-up'}}</button></fieldset><p class="small muted">A promise does not record a payment. Use Record payment when money actually changes hands.</p></section>}
<p class="error" role="alert">{{error()}}</p><p class="success" role="status">{{message()}}</p><div class="followup-history">@for(entry of history();track entry['id']){<article class="note"><div class="panel-heading"><strong>{{entry['kind']}}</strong><small>{{text(entry['createdAtUtc'])|date:'dd MMM, HH:mm'}}</small></div><p>{{entry['note']}}</p>@if(entry['promiseDate']){<small>Promised: {{text(entry['promiseDate'])|date:'dd MMM yyyy'}} @if(entry['amount']){· {{number(entry['amount'])|currency:'INR'}}}</small>}@if(entry['nextContactDate']){<small>Next contact: {{text(entry['nextContactDate'])|date:'dd MMM yyyy'}}</small>}</article>}@empty{<p class="small muted">No follow-ups recorded yet.</p>}@if(total()>25){<div class="pagination"><button type="button" class="quiet" [disabled]="page===1" (click)="page=page-1;load()">Previous</button><span>Page {{page}}</span><button type="button" class="quiet" [disabled]="page*25>=total()" (click)="page=page+1;load()">Next</button></div>}</div>`})
export class CustomerFollowUp {
 readonly customer=input.required<Row>();readonly changed=output<void>();readonly auth=inject(AuthService);private api=inject(ApiService);private branch=inject(BranchContext);private fb=inject(FormBuilder);readonly error=signal('');readonly message=signal('');readonly busy=signal(false);readonly history=signal<Row[]>([]);readonly total=signal(0);page=1;private version=0;private selectedCustomer='';readonly shop=signal<{name:string;phone:string}|null>(null);readonly promiseDate=signal<string|null>(null);
 readonly phone=new FormControl('',{nonNullable:true});readonly reminder=new FormControl('',{nonNullable:true});private today=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'});readonly from=new FormControl(this.today.slice(0,8)+'01',{nonNullable:true});readonly to=new FormControl(this.today,{nonNullable:true});readonly form=this.fb.nonNullable.group({kind:['Promise'],promiseDate:[''],amount:[''],nextContactDate:[''],note:['',Validators.required]});
 constructor(){effect(()=>{const c=this.customer();untracked(()=>{const id=String(c['customerId']??c['id']);if(id===this.selectedCustomer){if(this.reminder.pristine)this.resetMessage();void this.load();return;}this.selectedCustomer=id;this.phone.setValue(String(c['phone']??''));this.history.set([]);this.promiseDate.set(c['promiseDate']?String(c['promiseDate']):null);this.reminder.setValue(this.makeMessage(c));this.reminder.markAsPristine();this.page=1;void this.load();});});}
 phones(){return [this.customer()['phone'],this.customer()['alternatePhone']].map(v=>String(v??'')).filter(Boolean);}
 dialNumber(){const raw=this.phone.value.replace(/\D/g,'');return raw.length===10?'+91'+raw:'+'+raw;}
 whatsappLink(){return 'https://wa.me/'+this.dialNumber().replace('+','')+'?text='+encodeURIComponent(this.reminder.value);}
 smsLink(){return 'sms:'+this.dialNumber()+'?body='+encodeURIComponent(this.reminder.value);}
 makeMessage(c:Row){const trade=Number(c['tradeBalance']??c['outstanding']??0),independent=Number(c['independentBalance']??0);const money=(n:number)=>n.toLocaleString('en-IN',{style:'currency',currency:'INR'});const date=this.promiseDate();const promised=date?' by '+new Date(String(date)+'T12:00:00').toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}):'';const shop=this.shop();const signature=['Thank you,',shop?.name??'The shop',shop?.phone?'Contact: '+shop.phone:''].filter(Boolean).join('\n');const paragraphs=['Hello '+String(c['name']??c['customerName']??'')+','];if(trade>0||independent>0){paragraphs.push('This is a payment reminder from '+(shop?.name??'the shop')+'.');paragraphs.push([trade>0?'Sales / invoice dues: '+money(trade):'',independent>0?'Independent LenDen dues: '+money(independent):''].filter(Boolean).join('\n'));paragraphs.push('Please pay as promised'+promised+' to keep your account in good standing and avoid being recorded as a payment defaulter in our shop records.');paragraphs.push('If you need more time, please call us to agree a new payment date.');}else paragraphs.push('Please contact '+(shop?.name??'the shop')+' to review your account statement.');paragraphs.push(signature);return paragraphs.join('\n\n');}
 resetMessage(){this.reminder.setValue(this.makeMessage(this.customer()));this.reminder.markAsPristine();}
 text(v:unknown){return String(v??'');}number(v:unknown){return Number(v??0);}private customerId(){return String(this.customer()['customerId']??this.customer()['id']);}
 async load(){const version=++this.version;try{const result=await this.api.get<Page<Row>&{promiseDate:string|null;shop:{name:string;phone:string}}>('/customers/'+this.customerId()+'/followups?'+this.branch.query()+'&page='+this.page);if(version===this.version){this.shop.set(result.shop);this.history.set(result.items);this.promiseDate.set(result.promiseDate);this.total.set(result.totalItems);if(this.page===1&&this.reminder.pristine)this.resetMessage();}}catch(e){if(version===this.version)this.error.set(errorText(e));}}
 async save(){if(this.busy()||this.form.invalid)return;const v=this.form.getRawValue();if(v.kind==='Promise'&&!v.promiseDate)return;this.busy.set(true);this.error.set('');try{await this.api.mutate('/lenden/followups',{branchId:this.branch.id(),customerId:this.customerId(),kind:v.kind,note:v.note,promiseDate:v.kind==='Promise'?v.promiseDate:null,nextContactDate:v.nextContactDate||null,amount:v.kind==='Promise'&&v.amount?v.amount:null});this.form.patchValue({note:'',amount:'',promiseDate:'',nextContactDate:''});this.message.set('Follow-up saved. Account balances are unchanged.');await this.load();this.changed.emit();}catch(e){this.error.set(errorText(e));}finally{this.busy.set(false);}}
 async copyMessage(){try{await navigator.clipboard.writeText(this.reminder.value);this.message.set('Reminder copied.');}catch{this.message.set('Select the message text to copy it.');}}
 async statement(share:boolean){this.busy.set(true);this.error.set('');try{const path='/customers/'+this.customerId()+'/statement/pdf?'+this.branch.query()+'&from='+this.from.value+'&to='+this.to.value;const file=new File([await this.api.blob(path)],'customer-statement.pdf',{type:'application/pdf'});if(share&&navigator.canShare?.({files:[file]})){try{await navigator.share({files:[file],title:'Customer account statement'});}catch(e){if(!(e instanceof DOMException&&e.name==='AbortError'))throw e;}}else{this.api.saveBlob(file,file.name);if(share)this.message.set('Statement downloaded. Attach the PDF to WhatsApp or your message.');}}catch(e){this.error.set(errorText(e));}finally{this.busy.set(false);}}
 ngOnDestroy(){this.version++;}
}
