import {Component,inject,input,output} from '@angular/core';
import {FormArray,FormBuilder,ReactiveFormsModule} from '@angular/forms';
export const RAM_OPTIONS=['2 GB','3 GB','4 GB','6 GB','8 GB','12 GB','16 GB','24 GB'];
export const STORAGE_OPTIONS=['16 GB','32 GB','64 GB','128 GB','256 GB','512 GB','1 TB','2 TB'];
export function deviceForm(fb:FormBuilder){return fb.nonNullable.group({imei1:[''],imei2:[''],serial:[''],ram:[''],storage:[''],color:[''],unitCost:[''],sellingPrice:[''],mrp:['']});}
export type DeviceForm=ReturnType<typeof deviceForm>;
export interface DeviceDefaults {ram:string;storage:string;color:string;unitCost:string;sellingPrice:string;mrp:string}
export function devicePayload(rows:FormArray<DeviceForm>,defaults:DeviceDefaults){return rows.getRawValue().map(d=>({device:{imei1:d.imei1.trim()||null,imei2:d.imei2.trim()||null,serial:d.serial.trim()||null},ram:d.ram.trim()||defaults.ram,storage:d.storage.trim()||defaults.storage,color:d.color.trim()||defaults.color,unitCost:d.unitCost==null||d.unitCost===''?defaults.unitCost:d.unitCost,sellingPrice:d.sellingPrice==null||d.sellingPrice===''?defaults.sellingPrice:d.sellingPrice,mrp:d.mrp==null||d.mrp===''?defaults.mrp:d.mrp}));}
export function deviceError(rows:FormArray<DeviceForm>,mobile:boolean){if(!rows.length||rows.length>100)return 'Add 1–100 devices per entry.';const seen=new Set<string>();for(const row of rows.getRawValue()){if(mobile&&!row.imei1.trim()&&!row.imei2.trim())return 'Each mobile phone needs an IMEI.';if(!row.imei1.trim()&&!row.imei2.trim()&&!row.serial.trim())return 'Each device needs an IMEI or serial number.';for(const [kind,value] of [['IMEI',row.imei1],['IMEI',row.imei2],['SERIAL',row.serial]]){if(!value.trim())continue;if(kind==='IMEI'&&!/^\d{15}$/.test(value.trim()))return 'IMEI must have exactly 15 digits.';const key=kind+value.trim().toUpperCase();if(seen.has(key))return 'An identity is repeated in this entry.';seen.add(key);}for(const value of [row.unitCost,row.sellingPrice,row.mrp])if(value!=null&&value!==''&&(!Number.isFinite(Number(value))||Number(value)<0))return 'Device prices and costs must be valid positive amounts or zero.';}return '';}
@Component({selector:'invora-device-rows',standalone:true,imports:[ReactiveFormsModule],template:`
<div class="device-entry-heading"><strong>{{rows().length}} {{rows().length===1?'device':'devices'}} to receive</strong><button type="button" class="secondary" [disabled]="rows().length>=100" (click)="add()">+ Add another {{purchase()&&mobile()?'phone':'device'}}</button></div>
<p class="small muted">One row per physical device. Enter RAM, storage and colour for this device. Blank prices use the billing defaults; existing model specifications appear as hints.</p>
<datalist id="device-ram-options">@for(option of ramOptions;track option){<option [value]="option"></option>}</datalist><datalist id="device-storage-options">@for(option of storageOptions;track option){<option [value]="option"></option>}</datalist>
@for(row of rows().controls;track row;let i=$index){<fieldset [formGroup]="row" class="device-capture" [class.purchase-device-row]="purchase()"><legend>Device {{i+1}}</legend><div class="form-grid three"><label>IMEI 1<input formControlName="imei1" inputmode="numeric" maxlength="15" placeholder="Scan or enter 15 digits"></label><label>{{purchase()?'IMEI 2':'IMEI 2 (optional)'}}<input formControlName="imei2" inputmode="numeric" maxlength="15"></label><label>Serial number<input formControlName="serial" maxlength="100" [placeholder]="mobile()?'Optional':'Required if no IMEI'"></label></div><div class="form-grid three"><label>Device RAM<input formControlName="ram" aria-label="Device RAM" list="device-ram-options" maxlength="50" [placeholder]="defaults().ram||'e.g. 2 GB'"></label><label>Device storage<input formControlName="storage" aria-label="Device storage" list="device-storage-options" maxlength="50" [placeholder]="defaults().storage||'e.g. 32 GB'"></label><label>Device color<input formControlName="color" maxlength="100" [placeholder]="defaults().color||'Enter color'"></label></div><div class="form-grid three"><label>Device cost (₹)<input formControlName="unitCost" type="number" min="0" step="0.01" [placeholder]="defaults().unitCost"></label><label>Device selling price (₹)<input formControlName="sellingPrice" type="number" min="0" step="0.01" [placeholder]="defaults().sellingPrice"></label><label>Device MRP (₹)<input formControlName="mrp" type="number" min="0" step="0.01" [placeholder]="defaults().mrp"></label></div>@if(rows().length>1){<button type="button" class="secondary danger-action" (click)="remove(i)">Remove device {{i+1}}</button>}</fieldset>}
`})
export class DeviceRows {readonly purchase=input(false);readonly countChanged=output<number>();readonly rows=input.required<FormArray<DeviceForm>>();readonly defaults=input.required<DeviceDefaults>();readonly mobile=input(false);private fb=inject(FormBuilder);readonly ramOptions=RAM_OPTIONS;readonly storageOptions=STORAGE_OPTIONS;add(){this.rows().push(deviceForm(this.fb));this.countChanged.emit(this.rows().length);}remove(index:number){this.rows().removeAt(index);this.countChanged.emit(this.rows().length);}}
