import {Component,inject,input,output,signal,effect,OnDestroy} from '@angular/core';
import {FormBuilder,FormControl,ReactiveFormsModule,Validators} from '@angular/forms';
import {ApiService,BranchContext,errorText} from '../../core/api';import {AuthService} from '../../core/auth';import {Page,Party} from '../../core/models';import {ModalFrame} from './modal-frame';
@Component({selector:'invora-party-picker',standalone:true,imports:[ReactiveFormsModule,ModalFrame],templateUrl:'./party-picker.html'})
export class PartyPicker implements OnDestroy {
 readonly kind=input<'customer'|'supplier'>('customer');readonly value=input('');readonly compact=input(false);readonly selected=output<Party>();readonly cleared=output<void>();readonly auth=inject(AuthService);private api=inject(ApiService);private branches=inject(BranchContext);private fb=inject(FormBuilder);private timer:ReturnType<typeof setTimeout>|undefined;private version=0;readonly selectedParty=signal<Party|null>(null);readonly total=signal(0);page=1;
 readonly states=signal<{code:string;name:string}[]>([]);readonly selection=new FormControl('',{nonNullable:true});readonly search=new FormControl('',{nonNullable:true});readonly results=signal<Party[]>([]);readonly loading=signal(false);readonly error=signal('');readonly creating=signal(false);readonly busy=signal(false);readonly createError=signal('');readonly form=this.fb.nonNullable.group({name:['',Validators.required],phone:['',[Validators.required,Validators.pattern(/^[+\d ()-]{7,20}$/)]],alternatePhone:['',Validators.pattern(/^[+\d ()-]{7,20}$/)],email:['',Validators.email],address:[''],stateCode:[''],gstin:['']});
 constructor(){this.search.valueChanges.subscribe(()=>this.queueSearch());effect(()=>{const kind=this.kind(),id=this.value();this.selection.setValue(id,{emitEvent:false});void this.load(kind,id);});}
 private path(){return this.kind()==='supplier'?'/suppliers':'/customers';}
 options(){const list=this.results(),selected=this.selectedParty();return selected?.id===this.value()&&!list.some(p=>p.id===this.value())?[selected,...list]:list;}
 searchNow(event:Event){event.preventDefault();clearTimeout(this.timer);void this.load();}
 queueSearch(){this.page=1;this.loading.set(true);clearTimeout(this.timer);this.version++;this.timer=setTimeout(()=>void this.load(this.kind(),this.value()),200);}
 async load(kind=this.kind(),id=this.value()){const version=++this.version;this.loading.set(true);this.error.set('');try{const path=kind==='supplier'?'/suppliers':'/customers';const result=await this.api.get<Page<Party>>(path+'?pageSize=25&page='+this.page+'&search='+encodeURIComponent(this.search.value));if(version!==this.version)return;this.results.set(result.items);this.total.set(result.totalItems);if(id){this.selectedParty.set(result.items.find(p=>p.id===id)??(this.selectedParty()?.id===id?this.selectedParty():null));if(!this.selectedParty()){const detail=await this.api.get<{party:Party}>(path+'/'+id+'?'+this.branches.query());if(version===this.version)this.selectedParty.set(detail.party);}}else this.selectedParty.set(null);}catch(e){if(version===this.version)this.error.set(errorText(e));}finally{if(version===this.version)this.loading.set(false);}}
 choose(event:Event){const id=(event.target as HTMLSelectElement).value;if(!id){this.clear();return;}const party=this.options().find(p=>p.id===id);if(party)this.select(party);}
 select(party:Party){clearTimeout(this.timer);this.version++;this.loading.set(false);this.selectedParty.set(party);this.selection.setValue(party.id,{emitEvent:false});this.search.setValue('',{emitEvent:false});this.selected.emit(party);}
 clear(){this.selectedParty.set(null);this.selection.setValue('',{emitEvent:false});this.cleared.emit();}
 async openCreate(){this.createError.set('');this.form.reset({name:/\p{L}/u.test(this.search.value)?this.search.value:'',phone:/^[+\d ()-]+$/.test(this.search.value)?this.search.value:'',alternatePhone:'',email:'',address:'',stateCode:'',gstin:''});this.creating.set(true);try{const [settings,states]=await Promise.all([this.api.get<{stateCode:string}>('/billing-context'),this.api.get<{code:string;name:string}[]>('/gst-states')]);this.states.set(states);if(!this.form.controls.stateCode.value)this.form.controls.stateCode.setValue(settings.stateCode);}catch{/* State remains optional for this contact. */}}
 gstChanged(){const gst=this.form.controls.gstin.value.trim().toUpperCase();this.form.controls.gstin.setValue(gst);if(/^[0-9]{2}[A-Z0-9]{13}$/.test(gst))this.form.controls.stateCode.setValue(gst.slice(0,2));}
 async save(){if(this.busy()||this.form.invalid)return;this.busy.set(true);this.createError.set('');try{const v=this.form.getRawValue();const id=await this.api.mutate<string>(this.path(),{...v,name:v.name.trim(),phone:v.phone.trim(),creditLimit:null});const p=(await this.api.get<{party:Party}>(this.path()+'/'+id+'?'+this.branches.query())).party;this.selectedParty.set(p);this.results.update(list=>[p,...list.filter(x=>x.id!==id)]);this.search.setValue('',{emitEvent:false});this.creating.set(false);this.select(p);}catch(e){this.createError.set(errorText(e));}finally{this.busy.set(false);}}
 ngOnDestroy(){clearTimeout(this.timer);this.version++;}
}
