import {Component,ElementRef,inject,input,output,afterNextRender} from '@angular/core';
export interface PurchaseIdentity {imei1:string;imei2?:string;serial?:string}
export function emptyIdentity():PurchaseIdentity{return {imei1:'',imei2:'',serial:''};}
export function hasIdentity(device:PurchaseIdentity){return !!(device.imei1?.trim()||device.imei2?.trim()||device.serial?.trim());}
export function completeIdentity(device:PurchaseIdentity,mobile:boolean){const imeis=[device.imei1??'',device.imei2??''].filter(x=>x.trim());return imeis.every(x=>/^\d{15}$/.test(x.trim()))&&(mobile?imeis.length>0:hasIdentity(device));}
@Component({selector:'invora-purchase-identities',standalone:true,template:`
<section class="purchase-identities" [attr.aria-label]="'Device identities for '+name()">
<div class="identity-heading"><div><strong>{{mobile()?'Phone IMEIs':'Device identities'}}</strong><small>{{captured()}} of {{devices().length}} complete · {{active()?'Scans go to this item':'Click a field to scan into this item'}}</small></div><span class="badge" [class.positive]="captured()===devices().length">{{captured()===devices().length?'Ready':(devices().length-captured())+' remaining'}}</span>@if(canAdd()&&devices().length<100){<button type="button" class="secondary" (click)="add()">+ Add another {{mobile()?'phone':'device'}}</button>}</div>
@for(device of devices();track $index;let i=$index){<fieldset class="purchase-device-row" (focusin)="activated.emit()"><legend>Device {{i+1}}</legend><div class="form-grid three"><label>IMEI 1<input [value]="device.imei1" inputmode="numeric" maxlength="15" [placeholder]="mobile()?'Required · 15 digits':'Optional'" [attr.aria-invalid]="invalidImei(device.imei1)" (input)="change(i,'imei1',$event)" (keydown.enter)="$event.preventDefault()"></label><label>IMEI 2<input [value]="device.imei2??''" inputmode="numeric" maxlength="15" placeholder="Optional · second SIM" [attr.aria-invalid]="invalidImei(device.imei2)" (input)="change(i,'imei2',$event)" (keydown.enter)="$event.preventDefault()"></label><label>Serial number<input [value]="device.serial??''" maxlength="100" [placeholder]="mobile()?'Optional':'Required if no IMEI'" (input)="change(i,'serial',$event)" (keydown.enter)="$event.preventDefault()"></label></div>@if(canAdd()&&devices().length>1){<button type="button" class="secondary danger-action" (click)="removed.emit(i)">Remove device {{i+1}}</button>}@if(hasIdentity(device)){<button type="button" class="text-link" (click)="clear(i)">Clear device {{i+1}}</button>}@if(invalidImei(device.imei1)||invalidImei(device.imei2)){<small class="identity-error">IMEI must contain exactly 15 digits.</small>}</fieldset>}
</section>`})
export class PurchaseIdentities {
 readonly autofocus=input(true);readonly canAdd=input(false);readonly added=output<void>();readonly removed=output<number>();readonly devices=input.required<PurchaseIdentity[]>();readonly mobile=input(false);readonly name=input('product');readonly active=input(false);readonly changed=output<PurchaseIdentity[]>();readonly activated=output<void>();private element:ElementRef<HTMLElement>=inject(ElementRef);readonly hasIdentity=hasIdentity;
 constructor(){afterNextRender(()=>{if(!this.autofocus())return;const input=this.element.nativeElement.querySelector<HTMLInputElement>('input');input?.focus({preventScroll:true});});}
 add(){this.added.emit();setTimeout(()=>{const fields=this.element.nativeElement.querySelectorAll<HTMLInputElement>('.purchase-device-row input');fields[fields.length-3]?.focus();},0);}
 captured(){return this.devices().filter(d=>completeIdentity(d,this.mobile())).length;}
 invalidImei(value?:string){return !!value?.trim()&&!/^\d{15}$/.test(value.trim());}
 change(index:number,key:'imei1'|'imei2'|'serial',event:Event){this.activated.emit();const value=(event.target as HTMLInputElement).value;this.changed.emit(this.devices().map((d,i)=>i===index?{...d,[key]:value}:d));}
 clear(index:number){this.changed.emit(this.devices().map((d,i)=>i===index?emptyIdentity():d));}
}
