import {Component,inject,output,signal} from '@angular/core';
import {FormBuilder,ReactiveFormsModule,Validators} from '@angular/forms';
import {ApiService,BranchContext,errorText} from '../../core/api';
import {AuthService} from '../../core/auth';
import {Page,Product,Unit} from '../../core/models';
import {ModalFrame} from './modal-frame';
import {DeviceRows,deviceForm,devicePayload,deviceError} from './device-rows';
@Component({selector:'invora-stock-editor',standalone:true,imports:[ReactiveFormsModule,ModalFrame,DeviceRows],template:`
<invora-modal title="Opening stock / adjustment" eyebrow="PHYSICAL STOCK COUNT" [busy]="busy()" (closed)="closed.emit()">
<p class="muted modal-intro">Record stock already in the shop, or write off identified devices. New supplier invoices belong in Purchases.</p>
<fieldset [formGroup]="form" class="plain-fieldset"><label>Find model / variant<input type="search" formControlName="search" placeholder="Name, brand, RAM, color or SKU" (input)="queueSearch()"></label><label>Product<select formControlName="productId" (change)="selectProduct()"><option value="">Choose product</option>@for(p of products();track p.id){<option [value]="p.id">{{p.brand}} {{p.name}} · {{p.ram}} {{p.storage}} {{p.color}} · {{p.sku}}</option>}</select></label>
@if(product()){<label>Adjustment<select formControlName="action" (change)="loadAvailable()"><option value="add">Add existing stock</option><option value="remove">Write off / reduce stock</option></select></label><label>Reason<input formControlName="reason" placeholder="Opening inventory counted in shop" required></label>
@if(product()!.serialized){@if(form.controls.action.value==='add'){@if(auth.can('inventory.cost.view')){<label>Default cost per device (₹)<input formControlName="unitCost" type="number" min="0" step="0.01"></label><invora-device-rows [rows]="devices" [defaults]="defaults()" [mobile]="mobile()"/>}@else{<p class="panel-note">Cost permission is required to add devices with their purchase values.</p>}}@else{<label>Find available IMEI / serial<input type="search" formControlName="identity" (input)="queueUnits()"></label><p class="small muted">{{selected().length}} devices selected. Removal never changes the recorded memory or color.</p><div class="device-options">@for(unit of units();track unit.id){<button type="button" class="device-option" [class.selected-row]="has(unit.id)" [disabled]="loading()||busy()" (click)="toggle(unit)"><span><strong>{{unit.identifiers.join(' · ')}}</strong><small>{{unit.description}}</small></span><span>{{has(unit.id)?'Selected ✓':'Select'}}</span></button>}@empty{<p class="empty-panel">{{loading()?'Looking up stock…':'No available devices found.'}}</p>}</div><div class="pagination"><button type="button" class="quiet" [disabled]="page===1||loading()" (click)="page=page-1;loadAvailable()">← Previous</button><span>Page {{page}}</span><button type="button" class="quiet" [disabled]="page*25>=total||loading()" (click)="page=page+1;loadAvailable()">Next →</button></div>}}
@else{<div class="form-grid"><label>Quantity<input formControlName="quantity" type="number" min="1" max="100000"></label>@if(form.controls.action.value==='add'){<label>Cost per unit (₹)<input formControlName="unitCost" type="number" min="0" step="0.01"></label>}</div>}}
</fieldset><p class="small muted">{{validation()}}</p><p class="error" role="alert">{{error()}}</p><div class="form-footer"><button type="button" class="secondary" [disabled]="busy()" (click)="closed.emit()">Cancel</button><button type="button" class="primary" [disabled]="busy()||form.invalid||!!validation()" (click)="save()">{{busy()?'Saving…':'Save stock adjustment'}}</button></div></invora-modal>
`})
export class StockEditor {
 readonly closed=output<void>();readonly saved=output<void>();readonly auth=inject(AuthService);private api=inject(ApiService);private branch=inject(BranchContext);private fb=inject(FormBuilder);readonly products=signal<Product[]>([]);readonly product=signal<Product|null>(null);readonly units=signal<Unit[]>([]);readonly selected=signal<Unit[]>([]);readonly busy=signal(false);readonly loading=signal(false);readonly error=signal('');readonly devices=this.fb.array([deviceForm(this.fb)]);private productTimer:ReturnType<typeof setTimeout>|undefined;private unitTimer:ReturnType<typeof setTimeout>|undefined;private version=0;private unitVersion=0;page=1;total=0;
 readonly form=this.fb.nonNullable.group({search:[''],productId:['',Validators.required],action:['add'],reason:['Opening inventory counted in shop',Validators.required],quantity:['1'],unitCost:['0'],identity:['']});
 constructor(){void this.search();}
 queueSearch(){clearTimeout(this.productTimer);this.version++;this.productTimer=setTimeout(()=>void this.search(),200);}
 async search(){const version=++this.version;try{const result=await this.api.get<Page<Product>>('/products?pageSize=100&search='+encodeURIComponent(this.form.controls.search.value));if(version===this.version){const selected=this.product();this.products.set(selected&&!result.items.some(p=>p.id===selected.id)?[selected,...result.items]:result.items);}}catch(e){if(version===this.version)this.error.set(errorText(e));}}
 selectProduct(){this.product.set(this.products().find(p=>p.id===this.form.controls.productId.value)??null);this.selected.set([]);this.units.set([]);this.devices.clear();this.devices.push(deviceForm(this.fb));this.page=1;void this.loadAvailable();}
 mobile(){return this.product()?.requiresImei||['mobile','smartphone','phone','mobile phone'].includes(this.product()?.category.trim().toLowerCase()??'');}
 defaults(){const p=this.product();return {ram:p?.ram??'',storage:p?.storage??'',color:p?.color??'',unitCost:String(this.form.controls.unitCost.value),sellingPrice:p?.sellingPrice??'0',mrp:p?.mrp??'0'};}
 queueUnits(){clearTimeout(this.unitTimer);this.page=1;this.unitVersion++;this.unitTimer=setTimeout(()=>void this.loadAvailable(),200);}
 async loadAvailable(){const version=++this.unitVersion;const p=this.product();if(!p||this.form.controls.action.value!=='remove'){this.units.set([]);this.loading.set(false);return;}this.loading.set(true);try{const result=await this.api.get<Page<Unit>>('/inventory?'+this.branch.query()+'&availableOnly=true&productVariantId='+p.id+'&pageSize=25&page='+this.page+'&search='+encodeURIComponent(this.form.controls.identity.value));if(version===this.unitVersion){this.units.set(result.items);this.total=result.totalItems;}}catch(e){if(version===this.unitVersion)this.error.set(errorText(e));}finally{if(version===this.unitVersion)this.loading.set(false);}}
 has(id:string){return this.selected().some(u=>u.id===id);}toggle(unit:Unit){this.selected.update(rows=>this.has(unit.id)?rows.filter(u=>u.id!==unit.id):[...rows,unit]);}
 validation(){const p=this.product();if(!p)return 'Choose a product.';const v=this.form.getRawValue();if(v.action==='add'&&(v.unitCost==null||v.unitCost===''||!Number.isFinite(Number(v.unitCost))||Number(v.unitCost)<0))return 'Enter a valid cost.';if(p.serialized)return v.action==='add'?this.auth.can('inventory.cost.view')?deviceError(this.devices,this.mobile()):'Cost permission is required.':this.selected().length?'':'Select every device being written off.';return Number.isInteger(Number(v.quantity))&&Number(v.quantity)>0&&Number(v.quantity)<=100000?'':'Enter a quantity from 1 to 100,000.';}
 async save(){if(this.busy()||this.form.invalid||this.validation())return;this.busy.set(true);this.error.set('');try{const v=this.form.getRawValue(),p=this.product()!;if(p.serialized&&v.action==='add')await this.api.mutate('/inventory/devices',{branchId:this.branch.id(),productVariantId:p.id,reason:v.reason,devices:devicePayload(this.devices,this.defaults())});else{const captures=this.selected().map(u=>{const identifiers=u.identifiers;return {imei1:identifiers.find(i=>i.startsWith('IMEI1: '))?.slice(7)||null,imei2:identifiers.find(i=>i.startsWith('IMEI2: '))?.slice(7)||null,serial:identifiers.find(i=>i.startsWith('SERIAL: '))?.slice(8)||null,trackingTag:identifiers.find(i=>i.startsWith('SHOP: '))?.slice(6)||null};});await this.api.mutate('/inventory/adjustments',{branchId:this.branch.id(),productVariantId:p.id,quantity:p.serialized?-captures.length:Number(v.quantity)*(v.action==='remove'?-1:1),unitCost:v.unitCost,reason:v.reason,devices:p.serialized?captures:null});}this.saved.emit();}catch(e){this.error.set(errorText(e));}finally{this.busy.set(false);}}
 ngOnDestroy(){clearTimeout(this.productTimer);clearTimeout(this.unitTimer);this.version++;this.unitVersion++;}
}
