<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><ProjectReference Include="../Invora.Domain/Invora.Domain.csproj" /><ProjectReference Include="../Invora.Application/Invora.Application.csproj" /><PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" /><PackageReference Include="Microsoft.Extensions.Identity.Core" /><PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" /><PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" /><PackageReference Include="Microsoft.EntityFrameworkCore" /><PackageReference Include="Microsoft.EntityFrameworkCore.Relational" /><PackageReference Include="PDFsharp-MigraDoc" /></ItemGroup><ItemGroup><EmbeddedResource Include="Pdf/Fonts/*.ttf" /></ItemGroup></Project>