import {ownerSession} from './session';
import {test,expect} from '@playwright/test';import {readFileSync} from 'node:fs';
const environmentPath=process.env['INVORA_E2E_ENV'];test.skip(!environmentPath,'Use an isolated development database for these posting tests.');const config:Record<string,string>=environmentPath?JSON.parse(readFileSync(environmentPath,'utf8')):{};
const credentials={login:'browser-owner',password:'Browser-test-password-2026'};const stamp=Date.now();const imei=String(stamp).padStart(15,'4');const customerName='Counter Customer '+stamp;let token='',branch='',product='',customer='',netSalesBefore=0;
test.beforeAll(async({request})=>{const session=await ownerSession(request,{tradeName:'Isolated Counter Test Store',branchCode:'MAIN',branchName:'Test counter',ownerLogin:credentials.login,ownerName:'Test Owner',password:credentials.password});token=session.accessToken;branch=session.user.branchIds[0];const summary=await request.get('/api/v1/dashboard/summary?branchId='+branch,{headers:{Authorization:'Bearer '+token}});netSalesBefore=Number((await summary.json()).netSales);});
test.beforeEach(async({page})=>{await page.goto('/login');await page.getByLabel('Login',{exact:true}).fill(credentials.login);await page.getByLabel('Password',{exact:true}).fill(credentials.password);await page.getByRole('button',{name:'Sign in →'}).click();await expect(page).toHaveURL(/\/$/);});
test('new product can configure its tax and capture IMEI plus serial in one save',async({page,request})=>{
 await page.route('**/api/v1/tax-rates',async route=>route.request().method()==='GET'?route.fulfill({status:200,contentType:'application/json',body:'[]'}):route.continue());await page.goto('/catalog');await page.getByRole('button',{name:'+ Add product',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByLabel('Display / item name',{exact:true}).fill('Counter Phone '+stamp);await dialog.getByLabel('Brand',{exact:true}).fill('Samsung');await dialog.getByLabel('Category',{exact:true}).fill('Mobile');await dialog.getByLabel('Selling price (₹)',{exact:true}).fill('9999');await dialog.getByLabel('MRP (₹)',{exact:true}).fill('12000');
 if(await dialog.getByLabel('Tax name',{exact:true}).isVisible()){await dialog.getByLabel('Tax name',{exact:true}).fill('Counter GST 0%');await dialog.getByRole('button',{name:'Save tax rate',exact:true}).click();}else{await dialog.getByRole('combobox',{name:'Tax rate',exact:true}).selectOption({index:1});}
 await dialog.getByLabel('Add stock already in this shop now',{exact:true}).check();await dialog.getByLabel('Cost per unit (₹)',{exact:true}).fill('5000');await dialog.getByLabel('Device RAM',{exact:true}).fill('8 GB');await dialog.getByLabel('Device storage',{exact:true}).fill('128 GB');await dialog.getByLabel('Device color',{exact:true}).fill('Green');await dialog.getByLabel('IMEI 1',{exact:true}).fill(imei);await dialog.getByLabel('IMEI 2 (optional)',{exact:true}).fill(String(BigInt(imei)+1n));await dialog.getByLabel('Serial number',{exact:true}).fill('PHONE-'+stamp);await dialog.getByRole('button',{name:'Save product & stock',exact:true}).click();await expect(dialog).toHaveCount(0);const found=await request.get('/api/v1/products?search='+encodeURIComponent('Counter Phone '+stamp),{headers:{Authorization:'Bearer '+token}});expect(found.ok()).toBeTruthy();product=(await found.json()).items[0].id;await expect(page.locator('tbody')).toContainText('Counter Phone '+stamp);
});
test('manual device choice and inline customer creation preserve the sale cart',async({page,request})=>{
 await page.goto('/sales/new');await page.getByRole('combobox',{name:'Product',exact:true}).selectOption(product);await page.getByRole('button',{name:'+ Add product',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:new RegExp(imei)}).click();await expect(page.locator('tbody')).toContainText(imei);
 await page.getByRole('searchbox',{name:'Find customer',exact:true}).fill('9000000029');await expect(page.getByRole('searchbox',{name:'Find customer',exact:true})).toHaveValue('9000000029');await page.getByRole('button',{name:'+ New customer',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByLabel('Name',{exact:true}).fill(customerName);await expect(dialog.getByLabel('Mobile number',{exact:true})).toHaveValue('9000000029');await dialog.getByRole('button',{name:'Save & select customer',exact:true}).click();await expect(dialog).toHaveCount(0);const found=await request.get('/api/v1/customers?search='+encodeURIComponent(customerName),{headers:{Authorization:'Bearer '+token}});customer=(await found.json()).items[0].id;await expect(page.getByRole('combobox',{name:'Customer',exact:true})).toHaveValue(customer);await expect(page.locator('tbody')).toContainText(imei);
 await page.getByLabel('Cash received').fill('9999');await page.getByRole('button',{name:'Review totals',exact:true}).click();await page.getByRole('button',{name:'Complete sale',exact:true}).click();await expect(page).toHaveURL(/\/sales\/[0-9a-f-]+$/);await expect(page.locator('p.error').filter({hasText:/./})).toHaveCount(0);
});
test('independent LenDen records money without an invoice and keeps a separate balance',async({page,request})=>{
 await page.goto('/lenden');await page.getByRole('link',{name:'+ Give / receive money',exact:true}).click();await page.getByRole('searchbox',{name:'Find customer',exact:true}).fill('+91 90000 00029');await expect(page.getByRole('combobox',{name:'Customer',exact:true}).locator('option').filter({hasText:customerName})).toHaveCount(1);await page.getByRole('combobox',{name:'Customer',exact:true}).selectOption(customer);await page.getByLabel('Amount',{exact:true}).fill('1000');await page.getByLabel('Reason for LenDen',{exact:true}).fill('Loan without any invoice');await page.getByRole('button',{name:'Record LenDen',exact:true}).click();await expect(page).toHaveURL(/\/lenden$/);await page.getByRole('searchbox',{name:'Find LenDen customer'}).fill('9000000029');const row=page.locator('tbody tr').filter({hasText:customerName});await expect(row).toContainText('1,000.00');await row.getByRole('link',{name:'Receive',exact:true}).click();await expect(page).toHaveURL(/\/lenden\/new\?/);await expect(page.getByRole('heading',{name:'Record LenDen',exact:true})).toBeVisible();await page.getByLabel('Amount',{exact:true}).fill('400');await expect(page.getByLabel('Amount',{exact:true})).toHaveValue('400');await page.getByLabel('Reason for LenDen',{exact:true}).fill('Partial repayment');await page.getByRole('button',{name:'Record LenDen',exact:true}).click();await expect(page).toHaveURL(/\/lenden$/);await page.getByRole('searchbox',{name:'Find LenDen customer'}).fill('9000000029');await expect(page.locator('tbody tr').filter({hasText:customerName})).toContainText('600.00');
 const summary=await request.get('/api/v1/dashboard/summary?branchId='+branch,{headers:{Authorization:'Bearer '+token}});expect(summary.ok()).toBeTruthy();expect(Number((await summary.json()).netSales)).toBe(netSalesBefore+9999);await expect(page.locator('tbody')).not.toContainText('Browser Customer');await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'../artifacts/lenden-independent.png',fullPage:true});
});
test('cashier can find and add a customer without settings or owner permission',async({page,request})=>{
 const tax=await request.get('/api/v1/tax-rates',{headers:{Authorization:'Bearer '+token}});const rates=await tax.json();const created=await request.post('/api/v1/products',{headers:{Authorization:'Bearer '+token,'Idempotency-Key':crypto.randomUUID()},data:{name:'Counter accessory',brand:'Test',category:'Accessory',hsn:'8544',taxRateId:rates[0].id,sku:'CASHIER-'+stamp,barcode:null,ram:'',storage:'',color:'Black',serialized:false,sellingPrice:'100',mrp:'100',warrantyMonths:0}});expect(created.ok(),await created.text()).toBeTruthy();const accessory=await created.json();
 const staff=await request.post('/api/v1/users',{headers:{Authorization:'Bearer '+token},data:{login:'cashier-'+stamp,displayName:'Cashier',password:'Cashier-test-password-2026',permissions:['inventory.view','sales.view','sales.create','customers.view','customers.manage','payments.create','payments.view'],branchIds:[branch]}});expect(staff.ok(),await staff.text()).toBeTruthy();await page.goto('/login');await page.getByLabel('Login',{exact:true}).fill('cashier-'+stamp);await page.getByLabel('Password',{exact:true}).fill('Cashier-test-password-2026');await page.getByRole('button',{name:'Sign in →'}).click();await expect(page).toHaveURL(/\/account$/);await expect(page.locator('.sidebar-bottom')).toContainText('Cashier');await page.goto('/sales/new');await page.getByRole('combobox',{name:'Product',exact:true}).selectOption(accessory);await page.getByRole('button',{name:'+ Add product',exact:true}).click();await page.getByRole('button',{name:'+ New customer',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByLabel('Name',{exact:true}).fill('Cashier new customer');await dialog.getByLabel('Mobile number',{exact:true}).fill('9000000039');await dialog.getByRole('button',{name:'Save & select customer',exact:true}).click();await expect(dialog).toHaveCount(0);await expect(page.locator('tbody')).toContainText('Counter accessory');await expect(page.locator('p.error').filter({hasText:/./})).toHaveCount(0);await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'../artifacts/counter-sale-desktop.png',fullPage:true});
});
