import {ownerSession} from './session';
import {test,expect} from '@playwright/test';
import {readFileSync} from 'node:fs';
const environmentPath=process.env['INVORA_E2E_ENV'];test.skip(!environmentPath,'Use an isolated development database for posting tests.');
const config:Record<string,string>=environmentPath?JSON.parse(readFileSync(environmentPath,'utf8')):{};
const credentials={login:'browser-owner',password:'Browser-test-password-2026'};
const stamp=Date.now(),name='Variant Phone '+stamp,brand='Counter Brand '+stamp,imei1=String(stamp).padStart(15,'7'),imei2=String(BigInt(imei1)+1n),imei3=String(BigInt(imei1)+2n);
let token='',branch='';
test.beforeAll(async({request})=>{const session=await ownerSession(request,{tradeName:'Isolated Variant Test Store',branchCode:'MAIN',branchName:'Test counter',ownerLogin:credentials.login,ownerName:'Test Owner',password:credentials.password});token=session.accessToken;branch=session.user.branchIds[0];});
test('mixed phone identities, memory and colors can be received, found, sold and written off',async({page,request})=>{
 test.setTimeout(60000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/login');await page.getByLabel('Login',{exact:true}).fill(credentials.login);await page.getByLabel('Password',{exact:true}).fill(credentials.password);await page.getByRole('button',{name:'Sign in →'}).click();await expect(page).toHaveURL(/\/$/);
 await page.goto('/catalog');await page.getByRole('button',{name:'+ Add product',exact:true}).click();let dialog=page.getByRole('dialog');await dialog.getByLabel('Display / item name',{exact:true}).fill(name);await dialog.getByRole('button',{name:'+ Add new brand',exact:true}).click();await dialog.getByLabel('New brand name',{exact:true}).fill(brand);await dialog.getByRole('button',{name:'Save brand',exact:true}).click();await expect(dialog.getByLabel('Brand',{exact:true})).toHaveValue(brand);await expect(dialog.getByRole('combobox',{name:'Stock tracking',exact:true})).toHaveCount(0);await expect(dialog.getByLabel('Color',{exact:true})).toHaveCount(0);
 await dialog.getByLabel('Selling price (₹)',{exact:true}).fill('3000');await dialog.getByLabel('MRP (₹)',{exact:true}).fill('3500');await expect(dialog.locator('.tax-explanation')).toContainText('CGST 9% + SGST 9%');
 await dialog.getByLabel('Add stock already in this shop now',{exact:true}).check();await dialog.getByLabel('Cost per unit (₹)',{exact:true}).fill('1000');await dialog.getByRole('button',{name:'+ Add another device',exact:true}).click();const first=dialog.locator('.device-capture').nth(0),second=dialog.locator('.device-capture').nth(1);await first.getByLabel('Device RAM',{exact:true}).fill('2 GB');await first.getByLabel('Device storage',{exact:true}).fill('32 GB');await first.getByLabel('Device color',{exact:true}).fill('Blue');await first.getByLabel('IMEI 1',{exact:true}).fill(imei1);await first.getByLabel('Serial number',{exact:true}).fill('BLUE-'+stamp);await second.getByLabel('IMEI 1',{exact:true}).fill(imei2);await second.getByLabel('Serial number',{exact:true}).fill('BLACK-'+stamp);await second.getByLabel('Device RAM',{exact:true}).fill('3 GB');await second.getByLabel('Device storage',{exact:true}).fill('32 GB');await second.getByLabel('Device color',{exact:true}).fill('Black');await second.getByLabel('Device cost (₹)',{exact:true}).fill('1200');await second.getByLabel('Device selling price (₹)',{exact:true}).fill('3200');await second.getByLabel('Device MRP (₹)',{exact:true}).fill('4000');await page.screenshot({path:'../artifacts/mixed-phone-stock.png',fullPage:true});await dialog.getByRole('button',{name:'Save product & stock',exact:true}).click();await expect(dialog).toHaveCount(0);
 const headers={Authorization:'Bearer '+token};const variantsResponse=await request.get('/api/v1/products?search='+encodeURIComponent(name),{headers});expect(variantsResponse.ok()).toBeTruthy();const variants=(await variantsResponse.json()).items;expect(variants).toHaveLength(2);expect(new Set(variants.map((p:{productModelId:string})=>p.productModelId)).size).toBe(1);const blue=variants.find((p:{color:string})=>p.color==='Blue');const black=variants.find((p:{color:string})=>p.color==='Black');await page.getByRole('combobox',{name:'Category',exact:true}).selectOption('Mobile');await page.getByRole('combobox',{name:'Brand',exact:true}).selectOption(brand);await expect(page.locator('tbody tr')).toHaveCount(2);
 await page.goto('/sales/new');await page.getByRole('searchbox',{name:'Find product',exact:true}).fill(imei2);await page.locator('.stock-search-results').getByRole('button',{name:new RegExp(imei2)}).click();await expect(page.locator('tbody')).toContainText('3 GB 32 GB Black');await expect(page.getByRole('spinbutton',{name:'Item price',exact:true})).toHaveValue('3200.00');await page.getByRole('searchbox',{name:'Find product',exact:true}).fill(name);await expect(page.locator('.stock-search-results')).toContainText(imei1);await page.locator('.stock-search-results').getByRole('button',{name:new RegExp(imei1)}).click();await expect(page.locator('tbody tr')).toHaveCount(2);
 // Model chooser shows every available variant, and numeric serial scans also resolve the exact physical unit.
 await page.locator('tbody tr').filter({hasText:imei1}).getByRole('button',{name:'Remove item',exact:true}).click();await page.getByRole('combobox',{name:'Product',exact:true}).selectOption(blue.id);await page.getByRole('button',{name:'+ Add product',exact:true}).click();dialog=page.getByRole('dialog');await expect(dialog.getByRole('button',{name:new RegExp(imei2)})).toBeDisabled();await dialog.getByRole('button',{name:new RegExp(imei1)}).click();await expect(dialog).toHaveCount(0);await page.locator('tbody tr').filter({hasText:imei1}).getByRole('button',{name:'Remove item',exact:true}).click();await page.locator('tbody tr').filter({hasText:imei2}).getByRole('button',{name:'Remove item',exact:true}).click();await page.getByPlaceholder('Scan IMEI, serial or accessory barcode…').fill('BLACK-'+stamp);await page.getByPlaceholder('Scan IMEI, serial or accessory barcode…').press('Enter');await expect(page.locator('tbody')).toContainText('3 GB 32 GB Black');
 await page.getByRole('button',{name:'+ New customer',exact:true}).click();dialog=page.getByRole('dialog');await dialog.getByLabel('Name',{exact:true}).fill('Variant customer '+stamp);await dialog.getByLabel('Mobile number',{exact:true}).fill('9000000069');await dialog.getByRole('button',{name:'Save & select customer',exact:true}).click();await expect(dialog).toHaveCount(0);await page.getByLabel('Cash received').fill('3200');await page.getByRole('button',{name:'Review totals',exact:true}).click();await page.getByRole('button',{name:'Complete sale',exact:true}).click();await expect(page).toHaveURL(/\/sales\/[0-9a-f-]+$/);
 await page.goto('/inventory');await page.getByRole('button',{name:'+ Opening / adjust stock',exact:true}).click();dialog=page.getByRole('dialog');await dialog.getByRole('combobox',{name:'Product',exact:true}).selectOption(blue.id);await dialog.getByLabel('Default cost per device (₹)',{exact:true}).fill('1500');await dialog.getByLabel('IMEI 1',{exact:true}).fill(imei3);await dialog.getByLabel('Device RAM',{exact:true}).fill('4 GB');await dialog.getByLabel('Device storage',{exact:true}).fill('64 GB');await dialog.getByLabel('Device color',{exact:true}).fill('White');await dialog.getByRole('button',{name:'Save stock adjustment',exact:true}).click();await expect(dialog).toHaveCount(0);
 const more=await request.get('/api/v1/products?search='+encodeURIComponent(name),{headers});expect((await more.json()).items).toHaveLength(3);
 await page.getByRole('button',{name:'+ Opening / adjust stock',exact:true}).click();dialog=page.getByRole('dialog');await dialog.getByRole('combobox',{name:'Product',exact:true}).selectOption(blue.id);await dialog.getByRole('combobox',{name:'Adjustment',exact:true}).selectOption('remove');await dialog.getByRole('button',{name:new RegExp(imei1)}).click();await dialog.getByRole('button',{name:'Save stock adjustment',exact:true}).click();await expect(dialog).toHaveCount(0);const available=await request.get('/api/v1/inventory?branchId='+branch+'&productModelId='+black.productModelId+'&availableOnly=true',{headers});const units=(await available.json()).items;expect(units).toHaveLength(1);expect(units[0].identifiers).toContain('IMEI1: '+imei3);expect(errors).toEqual([]);
 // Receive a new memory/color configuration under the existing model, with a supplier payable.
 await page.goto('/purchases/new');await page.getByRole('combobox',{name:'Product',exact:true}).selectOption(blue.id);await page.getByRole('button',{name:'+ Another memory / color for this model',exact:true}).click();dialog=page.getByRole('dialog');await expect(dialog.getByLabel('Display / item name',{exact:true})).toHaveValue(name);await expect(dialog.getByLabel('Add stock already in this shop now',{exact:true})).toHaveCount(0);await dialog.getByLabel('Device RAM',{exact:true}).fill('6 GB');await dialog.getByLabel('Device storage',{exact:true}).fill('128 GB');await dialog.getByLabel('Device color',{exact:true}).fill('Green');await dialog.getByLabel('Selling price (₹)',{exact:true}).fill('3600');const imei4=String(BigInt(imei1)+3n);await dialog.getByLabel('Purchase cost per unit (₹)',{exact:true}).fill('1500');await dialog.getByLabel('IMEI 1',{exact:true}).fill(imei4);await dialog.getByRole('button',{name:'Save & add to purchase',exact:true}).click();await expect(dialog).toHaveCount(0);await expect(page.locator('tbody')).toContainText('6 GB 128 GB Green');await page.getByRole('spinbutton',{name:'Item price',exact:true}).fill('1500');await expect(page.locator('tbody')).toContainText(imei4);await page.getByRole('button',{name:'+ New supplier',exact:true}).click();dialog=page.getByRole('dialog');await dialog.getByLabel('Name',{exact:true}).fill('Variant supplier '+stamp);await dialog.getByLabel('Mobile number',{exact:true}).fill('9000000079');await dialog.getByRole('button',{name:'Save & select supplier',exact:true}).click();await expect(dialog).toHaveCount(0);await page.getByLabel('Supplier invoice number').fill('VARIANT-PURCHASE-'+stamp);await page.getByRole('button',{name:'Review totals',exact:true}).click();await page.getByRole('button',{name:'Complete purchase',exact:true}).click();await expect(page).toHaveURL(/\/purchases\/[0-9a-f-]+$/);await expect(page.locator('tbody')).toContainText('6 GB 128 GB Green');expect(errors).toEqual([]);
 await page.goto('/inventory');
 await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'+ Opening / adjust stock',exact:true}).click();dialog=page.getByRole('dialog');await dialog.getByRole('combobox',{name:'Product',exact:true}).selectOption(blue.id);await expect(dialog.locator('.device-entry-heading')).toContainText('1 device');expect(await dialog.evaluate(el=>el.scrollWidth<=el.clientWidth)).toBeTruthy();await page.screenshot({path:'../artifacts/mixed-phone-stock-mobile.png',fullPage:true});
});
