import {test,expect} from '@playwright/test';
import {ownerSession} from './session';

test.skip(!process.env['INVORA_E2E_ENV'],'Posting checks require an isolated database.');
test('guarded device corrections, used inspections and signed-off reminder paragraphs work on desktop and mobile',async({page,request})=>{
 test.setTimeout(90000);
 const stamp=Date.now(),imei=String(stamp).padStart(15,'8'),imei2=String(BigInt(imei)+1n),name='Tinu Ji '+stamp;
 const session=await ownerSession(request,{tradeName:'Correction fixture shop',branchCode:'MAIN',branchName:'Main counter',ownerLogin:'browser-owner',ownerName:'Test Owner',password:'Browser-test-password-2026'});
 const branch=session.user.branchIds[0],headers={Authorization:'Bearer '+session.accessToken};
 const post=async(path:string,data:unknown,method='POST')=>{const result=await request.fetch('/api/v1'+path,{method,headers:{...headers,'Idempotency-Key':crypto.randomUUID()},data});expect(result.ok(),await result.text()).toBeTruthy();return result.json();};
 const get=async(path:string)=>{const response=await request.get('/api/v1'+path,{headers});expect(response.ok(),await response.text()).toBeTruthy();return response.json();};
 const settings=await get('/settings');const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 try{
  await post('/settings',{...settings,phone:'9000000088'},'PUT');
  const customer=await post('/customers',{name,phone:'9'+String(stamp).slice(-9),stateCode:'23'});const taxes=await get('/tax-rates');const tax=taxes.find((t:{rate:string})=>Number(t.rate)===0).id;
  await post('/products/with-stock',{branchId:branch,quantity:2,unitCost:'0',reason:'Synthetic correction fixture',product:{name:'Correction Phone '+stamp,brand:'Samsung',category:'Mobile',hsn:'85171300',taxRateId:tax,sku:'CORRECTION-'+stamp,ram:'',storage:'',color:'',serialized:true,sellingPrice:'41499',mrp:'45000',warrantyMonths:12},deviceStock:[imei,imei2].map(id=>({device:{imei1:id},ram:'8 GB',storage:'128 GB',color:'Green',unitCost:'15000',sellingPrice:'41499',mrp:'45000'}))});
  const acquisition=await post('/device-acquisitions',{branchId:branch,customerId:customer,oldDevice:{name:'Used inspection '+stamp,brand:'Apple',ram:'4 GB',storage:'64 GB',color:'Black'},device:{},amount:'5000',method:1,condition:'Used',notes:'Initial battery inspection',batteryHealth:75,warrantyDays:0});
  await page.goto('/login');await page.getByLabel('Login',{exact:true}).fill('browser-owner');await page.getByLabel('Password',{exact:true}).fill('Browser-test-password-2026');await page.getByRole('button',{name:'Sign in →'}).click();await expect(page).toHaveURL(/\/$/);await page.getByRole('combobox',{name:'Active branch',exact:true}).selectOption(branch);
  await page.goto('/inventory');await page.getByRole('textbox',{name:'Search directory',exact:true}).fill(imei);await expect(page.locator('tbody tr')).toHaveCount(1);await page.getByRole('button',{name:'Edit device',exact:true}).click();let dialog=page.getByRole('dialog');await expect(dialog.getByRole('button',{name:'Save correction',exact:true})).toBeDisabled();await expect(dialog.locator('.device-summary')).toContainText(imei);
  await dialog.getByLabel('Colour',{exact:true}).fill('Blue');await dialog.getByLabel('Reason for correction',{exact:true}).fill('Colour checked against the phone and box.');await dialog.getByRole('button',{name:'Save correction',exact:true}).click();await expect(dialog.locator('.success')).toContainText('Device correction saved');await expect(dialog.locator('.correction-entry')).toContainText('Green → Blue');
  await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'../artifacts/device-correction-desktop.png',fullPage:true,animations:'disabled'});await dialog.getByRole('button',{name:'Close',exact:true}).click();await expect(page.locator('tbody')).toContainText('Blue');
  const scanned=await get('/inventory/scan?branchId='+branch+'&value='+imei),other=await get('/inventory/scan?branchId='+branch+'&value='+imei2);expect(scanned.unit.description).toContain('Blue');expect(other.unit.description).toContain('Green');expect(scanned.unit.identifiers).toContain('IMEI1: '+imei);
  await page.goto('/used-devices');const usedRow=page.locator('tbody tr').filter({hasText:'Used inspection '+stamp});await expect(usedRow).toContainText('No warranty');await usedRow.getByRole('button',{name:'Edit device',exact:true}).click();dialog=page.getByRole('dialog');await page.setViewportSize({width:375,height:812});await dialog.getByLabel('Battery health (%)',{exact:true}).fill('101');await dialog.getByLabel('Reason for correction',{exact:true}).fill('Retested battery after charging.');await expect(dialog.getByRole('button',{name:'Save correction',exact:true})).toBeDisabled();await dialog.getByLabel('Battery health (%)',{exact:true}).fill('82');await dialog.getByLabel('Inspection / accessories / repair notes',{exact:true}).fill('Battery retested; screen and cameras checked. Charger included.');await dialog.getByRole('button',{name:'Save correction',exact:true}).click();await expect(dialog.locator('.success')).toContainText('Device correction saved');await expect(dialog.locator('.correction-entry')).toContainText('75% → 82%');
  await expect.poll(()=>dialog.evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBeTruthy();await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();await dialog.evaluate(el=>el.scrollTop=0);await page.screenshot({path:'../artifacts/device-correction-mobile.png',fullPage:true,animations:'disabled'});await dialog.getByRole('button',{name:'Close',exact:true}).click();await expect(usedRow).toContainText('82%');
  const used=(await get('/used-devices?branchId='+branch)).find((r:{id:string})=>r.id===acquisition);expect(used.inspection.batteryHealth).toBe(82);expect(used.inspection.warrantyDays).toBe(0);
  const draft=await post('/sales',{branchId:branch,customerId:customer,businessDate:'2026-10-07',dueDate:'2026-10-15',interstate:false,items:[{productVariantId:scanned.unit.productVariantId,stockUnitId:scanned.unit.id,quantity:1,unitPrice:'41499'}],payments:[]});const sale=await post('/sales/'+draft.id+'/complete',{});const invoice=await get('/invoices/'+sale.id);expect(invoice.seller.warrantyTerms).toContain('authorized service centre');expect(invoice.lines[0].warrantyText).toContain('Service partner warranty: 12 months');
  await page.setViewportSize({width:1280,height:900});await page.goto('/lenden');await page.getByRole('searchbox',{name:'Find LenDen customer',exact:true}).fill(name);await expect(page.locator('tbody tr')).toHaveCount(1);await page.getByRole('button',{name:'Remind / promise',exact:true}).click();dialog=page.getByRole('dialog');const message=dialog.getByLabel('Reminder message',{exact:true});await expect(message).toHaveValue(/Contact: 9000000088$/);const text=await message.inputValue();expect(text).toContain('\n\nSales / invoice dues: ₹41,499.00\n\n');expect(text).toContain('payment defaulter in our shop records');expect(text).toContain('Thank you,\n');expect(text).not.toContain('bank defaulter');
  const custom='Custom reminder agreed with this customer.';await message.fill(custom);await dialog.getByLabel('Promised payment date',{exact:true}).fill('2026-10-15');await dialog.getByLabel('Conversation / reminder note',{exact:true}).fill('Promised on 15 October.');await dialog.getByRole('button',{name:'Save follow-up',exact:true}).click();await expect(dialog.locator('.followup-history')).toContainText('Promised on 15 October.');await expect(message).toHaveValue(custom);await dialog.getByRole('button',{name:'Use latest promise message',exact:true}).click();await expect(message).toHaveValue(/Please pay as promised by 15 Oct 2026/);await expect(message).toHaveValue(/Contact: 9000000088$/);await page.screenshot({path:'../artifacts/payment-reminder-paragraphs.png',fullPage:true,animations:'disabled'});expect(errors).toEqual([]);
 }finally{await post('/settings',settings,'PUT');}
});
