import {test,expect} from '@playwright/test';
import {ownerSession} from './session';

test.skip(!process.env['INVORA_E2E_ENV'],'Posting checks require an isolated database.');
test('dated GST invoices, both-phone lookup, stock filters and clear receive/pay ledgers work together',async({page,request})=>{
 test.setTimeout(90000);
 const stamp=Date.now(),customerName='Invoice customer '+stamp,phone='9'+String(stamp).slice(-9),alternate=String(BigInt(phone)+1n),imei=String(stamp).padStart(15,'6');
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 const session=await ownerSession(request,{tradeName:'Invoice fixture shop',branchCode:'MAIN',branchName:'Main counter',ownerLogin:'browser-owner',ownerName:'Owner',password:'Browser-test-password-2026'});
 const branch=session.user.branchIds[0],headers={Authorization:'Bearer '+session.accessToken};
 const post=async(path:string,data:unknown,method='POST')=>{
  const result=await request.fetch('/api/v1'+path,{method,headers:{...headers,'Idempotency-Key':crypto.randomUUID()},data});
  expect(result.ok(),await result.text()).toBeTruthy();return result.json();
 };
 const settings=await(await request.get('/api/v1/settings',{headers})).json();
 try{
  await post('/settings',{...settings,legalName:'Synthetic GST shop',address:'Synthetic address, Madhya Pradesh',stateCode:'23',gstin:'23ABCDE1234F1Z5',gstRegistered:true,compositionDealer:false},'PUT');
  const customer=await post('/customers',{name:customerName,phone,alternatePhone:alternate,stateCode:'07'});
  const taxes=await(await request.get('/api/v1/tax-rates',{headers})).json();const tax=taxes.find((t:{rate:string;cessRate:string})=>Number(t.rate)===18&&Number(t.cessRate)===0).id;
  await post('/products/with-stock',{product:{name:'Invoice phone '+stamp,brand:'Samsung',category:'Mobile',hsn:'85171300',taxRateId:tax,sku:'INVOICE-'+stamp,ram:'',storage:'',color:'',serialized:true,sellingPrice:'118',mrp:'150'},branchId:branch,quantity:1,unitCost:'50',reason:'Synthetic invoice stock',deviceStock:[{device:{imei1:imei},ram:'12 GB',storage:'256 GB',color:'Blue',unitCost:'50',sellingPrice:'118',mrp:'150'}]});
  await page.goto('/login');await page.getByLabel('Login',{exact:true}).fill('browser-owner');await page.getByLabel('Password',{exact:true}).fill('Browser-test-password-2026');await page.getByRole('button',{name:'Sign in →'}).click();await expect(page).toHaveURL(/\/$/);await page.getByRole('combobox',{name:'Active branch',exact:true}).selectOption(branch);
  await page.goto('/sales/new');const scanner=page.getByRole('textbox',{name:'Scan IMEI, serial or barcode',exact:true});await scanner.fill(imei);await scanner.press('Enter');await expect(page.locator('tbody')).toContainText('12 GB 256 GB Blue');
  await page.getByRole('searchbox',{name:'Find customer',exact:true}).fill('+91 '+alternate);await page.locator('.contact-results').getByRole('button',{name:new RegExp(stamp.toString())}).click();await page.getByLabel('Due date for credit sale',{exact:true}).fill('2026-10-20');
  await page.getByRole('button',{name:'Review totals',exact:true}).click();await expect(page.locator('.posted-quote')).toContainText('Delhi (07) · IGST');await expect(page.locator('.posted-quote')).toContainText('₹18.00');
  await page.getByRole('button',{name:'Complete sale',exact:true}).click();await expect(page).toHaveURL(/\/sales\/[0-9a-f-]+$/);const saleId=page.url().split('/').pop()!;const sale=await(await request.get('/api/v1/sales/'+saleId,{headers})).json();expect(sale.number).toMatch(/^I-\d{2}[A-Za-z]{3}\d{2}-\d{6}$/);expect(sale.number.length).toBeLessThanOrEqual(16);expect(sale.reference).toMatch(/^INV-.+-MAIN-\d{2}[A-Za-z]{3}\d{2}-\d{6}$/);await expect(page.locator('h1')).toHaveText(sale.reference);
  const downloaded=page.waitForEvent('download');await page.getByRole('button',{name:'↓ Download invoice',exact:true}).click();await downloaded;
  await page.goto('/sales');const search=page.getByRole('textbox',{name:'Search directory',exact:true});
  for(const term of ['customer '+stamp,'+91 '+phone,'+91 '+alternate,sale.number,sale.reference]){await search.fill(term);await expect(page.locator('tbody tr')).toHaveCount(1);await expect(page.locator('tbody')).toContainText(customerName);}
  await page.screenshot({path:'../artifacts/invoice-customer-lookup.png',fullPage:true});
  await page.goto('/inventory');await page.getByRole('combobox',{name:'Brand',exact:true}).selectOption('Samsung');await page.getByRole('combobox',{name:'Stock status',exact:true}).selectOption('Sold');await page.getByRole('textbox',{name:'Search directory',exact:true}).fill(imei);await expect(page.locator('tbody tr')).toHaveCount(1);await expect(page.locator('tbody')).toContainText(imei);
  await page.getByRole('combobox',{name:'Stock status',exact:true}).selectOption('InStock');await expect(page.locator('tbody')).not.toContainText(imei);
  await post('/lenden/entries',{branchId:branch,customerId:customer,direction:'In',amount:'500',method:1,businessDate:'2026-10-07',reference:'',note:'Independent deposit, separate from invoice'});
  await page.goto('/lenden');await page.getByRole('searchbox',{name:'Find LenDen customer',exact:true}).fill(alternate);await expect(page.locator('tbody tr')).toHaveCount(1);await expect(page.locator('tbody')).toContainText(customerName);await expect(page.locator('tbody')).toContainText('Lena hai');await expect(page.locator('tbody')).toContainText('Dena hai');await expect(page.locator('tbody')).toContainText('₹118.00');await expect(page.locator('tbody')).toContainText('₹500.00');
  await page.getByRole('button',{name:'Remind / promise',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByLabel('Promised payment date',{exact:true}).fill('2026-10-08');await dialog.getByLabel('Conversation / reminder note',{exact:true}).fill('Customer promised invoice payment tomorrow');await dialog.getByRole('button',{name:'Save follow-up',exact:true}).click();await expect(dialog.getByLabel('Reminder message',{exact:true})).toHaveValue(/Please pay as promised by 08 Oct 2026/);await expect(dialog.getByLabel('Reminder message',{exact:true})).not.toHaveValue(/bank defaulter/i);await dialog.getByRole('button',{name:'Close dialog',exact:true}).click();
  await page.goto('/customers/'+customer);await expect(page.locator('.kpi-grid')).toContainText('Lena hai');await expect(page.locator('.kpi-grid')).toContainText('Dena hai');await page.getByRole('combobox',{name:'Statement account',exact:true}).selectOption('independent');await expect(page.locator('tbody tr')).toHaveCount(1);await expect(page.locator('tbody')).toContainText('Dena hai');await page.getByRole('combobox',{name:'Statement account',exact:true}).selectOption('trade');await expect(page.locator('tbody tr')).toHaveCount(1);await expect(page.locator('tbody')).toContainText('Lena hai');await page.screenshot({path:'../artifacts/clear-lenden-ledger.png',fullPage:true});
  const supplierName='Credit supplier '+stamp,supplier=await post('/suppliers',{name:supplierName,phone:'9000000490'});await post('/payments',{branchId:branch,partyId:supplier,amount:'100',method:1,businessDate:'2026-10-07',reference:'',note:'Supplier advance',allocations:[]});
  await page.goto('/suppliers');await page.getByRole('textbox',{name:'Search directory',exact:true}).fill(supplierName);await expect(page.locator('tbody tr')).toHaveCount(1);await expect(page.locator('tbody')).toContainText(supplierName);await expect(page.locator('tbody')).toContainText('Lena hai');await expect(page.locator('.kpi-grid')).toContainText('₹100.00');await page.screenshot({path:'../artifacts/supplier-money-picture.png',fullPage:true});
  await page.goto('/suppliers/'+supplier);await page.getByRole('link',{name:'Receive supplier refund',exact:true}).click();await expect(page.getByRole('combobox',{name:'Payment purpose',exact:true})).toHaveValue('refund');await expect(page.getByRole('combobox',{name:'Invoice allocation',exact:true})).toHaveCount(0);await page.getByLabel('Amount',{exact:true}).fill('100');await page.getByRole('button',{name:'Record payment',exact:true}).click();await expect(page).toHaveURL(/\/payments$/);const supplierDetail=await(await request.get('/api/v1/suppliers/'+supplier+'?branchId='+branch,{headers})).json();expect(Number(supplierDetail.balance)).toBe(0);
  expect(errors).toEqual([]);
 }finally{await post('/settings',settings,'PUT');}
});
