import {ownerSession} from './session';
import {test,expect} from '@playwright/test';import {readFileSync} from 'node:fs';
const environmentPath=process.env['INVORA_E2E_ENV'];test.skip(!environmentPath,'Use an isolated development database for these posting tests.');const config:Record<string,string>=environmentPath?JSON.parse(readFileSync(environmentPath,'utf8')):{};
const credentials={login:'browser-owner',password:'Browser-test-password-2026'},stamp=Date.now(),brand='Purchase Brand '+stamp,category='Counter phones '+stamp,model='Easy Phone '+stamp;
const identities=[0,1,2,3].map(i=>String(BigInt(String(stamp).padStart(15,'8'))+BigInt(i)));let token='',branch='',customer='',supplier='',product='';
test.beforeAll(async({request})=>{const session=await ownerSession(request,{tradeName:'Purchase Test Store',branchCode:'MAIN',branchName:'Test counter',ownerLogin:credentials.login,ownerName:'Test Owner',password:credentials.password});token=session.accessToken;branch=session.user.branchIds[0];const post=async(path:string,data:unknown)=>{const response=await request.post('/api/v1'+path,{headers:{Authorization:'Bearer '+token,'Idempotency-Key':crypto.randomUUID()},data});expect(response.ok(),await response.text()).toBeTruthy();return response.json();};supplier=await post('/suppliers',{name:'Quick Purchase Vendor '+stamp,phone:'9000000099'});for(let i=0;i<26;i++)await post('/customers',{name:'Aardvark Contact '+stamp+' '+i,phone:'910001'+String(i).padStart(4,'0')});customer=await post('/customers',{name:'Zoya Lookup '+stamp,phone:'9000000098'});});
test.beforeEach(async({page})=>{await page.goto('/login');await page.getByLabel('Login',{exact:true}).fill(credentials.login);await page.getByLabel('Password',{exact:true}).fill(credentials.password);await page.getByRole('button',{name:'Sign in →'}).click();await expect(page).toHaveURL(/\/$/);});
test('purchase creates brand/category inline and requires an editable identity for every quantity',async({page,request})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/purchases/new');await page.getByRole('button',{name:'+ Add brand',exact:true}).click();let dialog=page.getByRole('dialog');await dialog.getByLabel('New brand name',{exact:true}).fill(brand);await dialog.getByRole('button',{name:'Save brand',exact:true}).click();await expect(dialog).toHaveCount(0);
 await page.getByRole('button',{name:'+ Add category',exact:true}).click();dialog=page.getByRole('dialog');await dialog.getByLabel('New category name',{exact:true}).fill(category);await dialog.getByRole('combobox',{name:'Stock type',exact:true}).selectOption('mobile');await dialog.getByRole('button',{name:'Save category',exact:true}).click();await expect(dialog).toHaveCount(0);
 await page.getByRole('button',{name:'+ Create new product here',exact:true}).click();dialog=page.getByRole('dialog');await expect(dialog.getByLabel('Brand',{exact:true})).toHaveValue(brand);await expect(dialog.getByLabel('Category',{exact:true})).toHaveValue(category);await expect(dialog.getByRole('combobox',{name:'Stock tracking',exact:true})).toHaveCount(0);await dialog.getByLabel('Display / item name',{exact:true}).fill(model);await dialog.getByLabel('Device RAM',{exact:true}).fill('3 GB');await dialog.getByLabel('Device storage',{exact:true}).fill('32 GB');await dialog.getByLabel('Device color',{exact:true}).fill('Green');await dialog.getByLabel('Selling price (₹)',{exact:true}).fill('1500');await dialog.getByLabel('MRP (₹)',{exact:true}).fill('1800');const saveProduct=dialog.getByRole('button',{name:'Save & add to purchase',exact:true});await expect(saveProduct).toBeDisabled();await dialog.getByLabel('Purchase cost per unit (₹)',{exact:true}).fill('1000');const modalRows=dialog.locator('.purchase-device-row');await modalRows.nth(0).getByLabel('IMEI 1',{exact:true}).fill(identities[0]);await modalRows.nth(0).getByLabel('IMEI 2',{exact:true}).fill(identities[3]);await modalRows.nth(0).getByLabel('Serial number',{exact:true}).fill('MANUAL-'+stamp);await dialog.getByRole('button',{name:'+ Add another phone',exact:true}).click();await expect(modalRows).toHaveCount(2);await expect(dialog.getByLabel('Purchase quantity',{exact:true})).toHaveValue('2');await expect(modalRows.nth(0).getByLabel('IMEI 1',{exact:true})).toHaveValue(identities[0]);await expect(saveProduct).toBeDisabled();await modalRows.nth(1).getByLabel('IMEI 1',{exact:true}).fill(identities[0]);await expect(dialog.locator('.purchase-receipt-editor')).toContainText('repeats an identity');await modalRows.nth(1).getByLabel('IMEI 1',{exact:true}).fill(identities[1]);await modalRows.nth(1).getByLabel('Device RAM',{exact:true}).fill('3 GB');await modalRows.nth(1).getByLabel('Device storage',{exact:true}).fill('32 GB');await modalRows.nth(1).getByLabel('Device color',{exact:true}).fill('Green');await page.screenshot({path:'../artifacts/new-purchase-product-identities.png',fullPage:true});await saveProduct.click();await expect(dialog).toHaveCount(0);
 const rows=page.locator('.purchase-device-row');await expect(rows).toHaveCount(2);await expect(page.getByRole('spinbutton',{name:'Item price',exact:true})).toHaveValue('1000');const beforePosting=await request.get('/api/v1/inventory?branchId='+branch+'&search='+encodeURIComponent(model),{headers:{Authorization:'Bearer '+token}});expect((await beforePosting.json()).items).toHaveLength(0);await rows.nth(0).getByLabel('IMEI 1',{exact:true}).fill(identities[0]);await rows.nth(0).getByLabel('IMEI 2',{exact:true}).fill(identities[3]);await rows.nth(0).getByLabel('Serial number',{exact:true}).fill('MANUAL-'+stamp);await page.getByRole('button',{name:'+ Add another phone',exact:true}).click();await expect(rows).toHaveCount(3);await expect(rows.nth(0).getByLabel('IMEI 1',{exact:true})).toHaveValue(identities[0]);await expect(rows.nth(0).getByLabel('IMEI 2',{exact:true})).toHaveValue(identities[3]);await expect(rows.nth(2).getByLabel('IMEI 1',{exact:true})).toHaveValue('');
 await page.getByRole('searchbox',{name:'Find supplier',exact:true}).fill('Vendor Quick '+stamp);await page.locator('.contact-results').getByRole('button',{name:new RegExp(stamp.toString())}).click();await expect(page.getByRole('combobox',{name:'Supplier',exact:true})).toHaveValue(supplier);await page.getByLabel('Supplier invoice number').fill('MANUAL-'+stamp);await expect(page.getByRole('button',{name:'Review totals',exact:true})).toBeDisabled();
 await rows.nth(1).getByLabel('IMEI 1',{exact:true}).fill(identities[0]);await expect(page.locator('.trade-summary .identity-error')).toContainText('repeats an identity');await rows.nth(1).getByLabel('IMEI 1',{exact:true}).fill(identities[1]);await page.getByRole('textbox',{name:'Scan IMEI, serial or barcode',exact:true}).fill(identities[2]);await page.getByRole('textbox',{name:'Scan IMEI, serial or barcode',exact:true}).press('Enter');await expect(rows.nth(2).getByLabel('IMEI 1',{exact:true})).toHaveValue(identities[2]);await expect(page.locator('.identity-heading')).toContainText('3 of 3 complete');
 await page.getByRole('spinbutton',{name:'Item quantity',exact:true}).fill('2');await page.getByLabel('Supplier invoice number').focus();await expect(page.getByRole('spinbutton',{name:'Item quantity',exact:true})).toHaveValue('3');await expect(rows).toHaveCount(3);await expect(page.locator('p.error').filter({hasText:/./})).toContainText('Clear the extra device identities');await page.getByRole('spinbutton',{name:'Item quantity',exact:true}).fill('3');await page.getByLabel('Supplier invoice number').focus();
 await page.screenshot({path:'../artifacts/purchase-identities-desktop.png',fullPage:true});await page.getByRole('button',{name:'Review totals',exact:true}).click();await page.getByRole('button',{name:'Complete purchase',exact:true}).click();await expect(page).toHaveURL(/\/purchases\/[0-9a-f-]+$/);expect(errors).toEqual([]);
 const headers={Authorization:'Bearer '+token};const products=await request.get('/api/v1/products?search='+encodeURIComponent(model),{headers});product=(await products.json()).items[0].id;const stock=await request.get('/api/v1/inventory?branchId='+branch+'&productVariantId='+product+'&availableOnly=true',{headers});const units=(await stock.json()).items;expect(units).toHaveLength(3);expect(units.flatMap((u:{identifiers:string[]})=>u.identifiers)).toContain('IMEI2: '+identities[3]);
 // Existing product results are clickable, and adding it displays a fresh identity row.
 await page.goto('/purchases/new');await page.getByRole('searchbox',{name:'Find product',exact:true}).fill(brand+' '+model+' 3/32');await page.locator('.purchase-product-results').getByRole('button',{name:new RegExp(model)}).click();await expect(page.locator('.purchase-device-row')).toHaveCount(1);await page.setViewportSize({width:390,height:844});await expect.poll(()=>page.locator('.sidebar').evaluate(element=>element.getBoundingClientRect().right)).toBeLessThanOrEqual(0);const phoneField=page.locator('.purchase-device-row').getByLabel('IMEI 1',{exact:true});await expect.poll(()=>phoneField.evaluate(element=>element.getBoundingClientRect().width)).toBeGreaterThan(200);await page.screenshot({path:'../artifacts/purchase-identities-mobile.png',fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
});
test('product/customer lookup uses visible matches, retains the cart and never submits on search Enter',async({page,request})=>{
 let quoteRequests=0;page.on('request',r=>{if(r.url().includes('/sales/quote'))quoteRequests++;});await page.goto('/sales/new');await page.getByRole('searchbox',{name:'Find product',exact:true}).fill(brand+' '+model+' 3/32');await page.getByRole('searchbox',{name:'Find product',exact:true}).press('Enter');await page.getByRole('combobox',{name:'Brand filter',exact:true}).selectOption('Apple');await expect(page.locator('.stock-search-results')).toContainText('No matching available phones');await page.getByRole('combobox',{name:'Brand filter',exact:true}).selectOption(brand);await page.getByRole('combobox',{name:'Category filter',exact:true}).selectOption(category);await page.locator('.stock-search-results').getByRole('button',{name:new RegExp(identities[0])}).click();await expect(page.locator('tbody')).toContainText(identities[0]);
 const customerSelect=page.getByRole('combobox',{name:'Customer',exact:true});await expect(customerSelect.locator('option[value="'+customer+'"]')).toHaveCount(0);await page.getByRole('searchbox',{name:'Find customer',exact:true}).fill('Lookup Zoya '+stamp);await page.getByRole('searchbox',{name:'Find customer',exact:true}).press('Enter');await page.locator('.contact-results').getByRole('button',{name:new RegExp('Zoya Lookup '+stamp)}).click();await expect(customerSelect).toHaveValue(customer);await expect(page.locator('.selected-contact')).toContainText('9000000098');await page.getByRole('button',{name:'Change customer',exact:true}).click();await expect(customerSelect).toHaveValue('');await expect(page.getByRole('button',{name:'Review totals',exact:true})).toBeDisabled();await page.getByRole('searchbox',{name:'Find customer',exact:true}).fill('+91 90000 00098');await page.locator('.contact-results').getByRole('button',{name:new RegExp('Zoya Lookup '+stamp)}).click();await expect(customerSelect).toHaveValue(customer);await page.getByLabel('Cash received').fill('1500');await page.getByRole('searchbox',{name:'Find customer',exact:true}).fill('Zoya Lookup '+stamp);await page.getByRole('searchbox',{name:'Find customer',exact:true}).press('Enter');await expect(page.locator('.contact-results')).toContainText('Zoya Lookup');expect(quoteRequests).toBe(0);await expect(page.locator('tbody')).toContainText(identities[0]);
 // Directory search responds to typing as well.
 await page.goto('/customers');await page.getByRole('textbox',{name:'Search directory',exact:true}).fill('Lookup Zoya '+stamp);await expect(page.locator('tbody tr')).toHaveCount(1);await expect(page.locator('tbody')).toContainText('Zoya Lookup');
 const global=page.getByRole('searchbox',{name:'Global search',exact:true});await global.fill('Lookup Zoya '+stamp);await page.locator('.workspace-lookup').getByRole('link',{name:new RegExp('Zoya Lookup '+stamp)}).click();await expect(page).toHaveURL(new RegExp('/customers/'+customer+'$'));
 await global.fill(brand+' '+model+' 3/32');await page.locator('.workspace-lookup').getByRole('link').filter({hasText:'Product'}).filter({hasText:model}).click();await expect(page).toHaveURL(/\/catalog\?search=/);await expect(page.locator('tbody tr')).toHaveCount(1);await expect(page.locator('tbody')).toContainText(model);
 await global.fill(identities[0]);await page.locator('.workspace-lookup').getByRole('link').filter({hasText:'Device'}).filter({hasText:identities[0]}).click();await expect(page).toHaveURL(/\/inventory\?search=/);await expect(page.locator('tbody tr')).toHaveCount(1);await expect(page.locator('tbody')).toContainText(identities[0]);
 await global.fill('Vendor Quick '+stamp);await page.locator('.workspace-lookup').getByRole('link').filter({hasText:'Supplier'}).click();await expect(page).toHaveURL(new RegExp('/suppliers/'+supplier+'$'));
 await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Search workspace',exact:true}).click();await page.getByRole('searchbox',{name:'Mobile workspace search',exact:true}).fill('Lookup Zoya '+stamp);await page.locator('.workspace-lookup').getByRole('link',{name:new RegExp('Zoya Lookup '+stamp)}).click();await expect(page).toHaveURL(new RegExp('/customers/'+customer+'$'));expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
});

test('new electronics receive quantity stock and serial devices through the supplier purchase',async({page,request})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));const headers={Authorization:'Bearer '+token};const taxes=await(await request.get('/api/v1/tax-rates',{headers})).json();const zero=taxes.find((t:{rate:string;cessRate:string})=>Number(t.rate)===0&&Number(t.cessRate)===0).id;const quantityName='Charger '+stamp,serialName='Monitor '+stamp,newBrand='Electronic Brand '+stamp,newCategory='Chargers '+stamp;
 await page.goto('/purchases/new');await page.getByRole('button',{name:'+ Create new product here',exact:true}).click();let dialog=page.getByRole('dialog');await dialog.getByLabel('Display / item name',{exact:true}).fill(quantityName);await dialog.getByRole('button',{name:'+ Add new brand',exact:true}).click();await dialog.getByLabel('New brand name',{exact:true}).fill(newBrand);await dialog.getByRole('button',{name:'Save brand',exact:true}).click();await dialog.getByRole('button',{name:'+ Add new category',exact:true}).click();await dialog.getByLabel('New category name',{exact:true}).fill(newCategory);await dialog.getByRole('combobox',{name:'Category stock type',exact:true}).selectOption('electronics');await dialog.getByRole('button',{name:'Save category',exact:true}).click();await dialog.getByRole('combobox',{name:'Stock tracking',exact:true}).selectOption('false');await dialog.getByLabel('HSN code',{exact:true}).fill('850440');await dialog.getByRole('combobox',{name:'Tax rate',exact:true}).selectOption(zero);await dialog.getByLabel('Selling price (₹)',{exact:true}).fill('350');await dialog.getByLabel('MRP (₹)',{exact:true}).fill('400');await dialog.getByLabel('Purchase quantity',{exact:true}).fill('4');await dialog.getByLabel('Purchase cost per unit (₹)',{exact:true}).fill('200');await expect(dialog.locator('.purchase-device-row')).toHaveCount(0);await dialog.getByRole('button',{name:'Save & add to purchase',exact:true}).click();await expect(dialog).toHaveCount(0);await expect(page.getByRole('spinbutton',{name:'Item quantity',exact:true})).toHaveValue('4');await expect(page.getByRole('spinbutton',{name:'Item price',exact:true})).toHaveValue('200');
 await page.getByRole('button',{name:'+ Create new product here',exact:true}).click();dialog=page.getByRole('dialog');await dialog.getByLabel('Display / item name',{exact:true}).fill(serialName);await dialog.getByLabel('Brand',{exact:true}).fill(newBrand);await dialog.getByLabel('Category',{exact:true}).fill('Electronics');await dialog.getByLabel('HSN code',{exact:true}).focus();await dialog.getByLabel('HSN code',{exact:true}).fill('852852');await dialog.getByRole('combobox',{name:'Tax rate',exact:true}).selectOption(zero);await dialog.getByRole('combobox',{name:'Stock tracking',exact:true}).selectOption('true');await dialog.getByLabel('Selling price (₹)',{exact:true}).fill('1500');await dialog.getByLabel('MRP (₹)',{exact:true}).fill('1800');await dialog.getByLabel('Purchase cost per unit (₹)',{exact:true}).fill('1000');await dialog.getByLabel('Serial number',{exact:true}).fill('MON-'+stamp);await dialog.getByRole('button',{name:'Save & add to purchase',exact:true}).click();await expect(dialog).toHaveCount(0);await expect(page.locator('tbody')).toContainText('MON-'+stamp);
 const before=await request.get('/api/v1/inventory?branchId='+branch+'&search='+encodeURIComponent(serialName),{headers});expect((await before.json()).items).toHaveLength(0);await page.getByRole('searchbox',{name:'Find supplier',exact:true}).fill('Vendor Quick '+stamp);await page.locator('.contact-results').getByRole('button',{name:new RegExp(stamp.toString())}).click();await page.getByLabel('Supplier invoice number').fill('ELECTRONICS-'+stamp);
 let releaseQuote=()=>{};const pendingQuote=new Promise<void>(resolve=>releaseQuote=resolve);await page.route('**/purchases/quote',async route=>{await pendingQuote;await route.continue();});await page.getByRole('button',{name:'Review totals',exact:true}).click();try{await expect(page.getByLabel('Supplier invoice number')).toBeDisabled();await expect(page.getByRole('spinbutton',{name:'Item price',exact:true}).first()).toBeDisabled();}finally{releaseQuote();}
 await page.getByRole('button',{name:'Complete purchase',exact:true}).click();await expect(page).toHaveURL(/\/purchases\/[0-9a-f-]+$/);const balances=await request.get('/api/v1/inventory/balances?branchId='+branch+'&search='+encodeURIComponent(quantityName),{headers});const quantities=(await balances.json()).items;expect(quantities).toHaveLength(1);expect(quantities[0].quantity).toBe(4);const devices=await request.get('/api/v1/inventory?branchId='+branch+'&availableOnly=true&search='+encodeURIComponent(serialName),{headers});const units=(await devices.json()).items;expect(units).toHaveLength(1);expect(units[0].identifiers).toEqual(['SERIAL: MON-'+stamp]);expect(Number(units[0].cost)).toBe(1000);expect(errors).toEqual([]);
});
