import {ownerSession} from './session';
import {test,expect} from '@playwright/test';
import {readFileSync} from 'node:fs';
const environmentPath=process.env['INVORA_E2E_ENV'];
test.skip(!environmentPath,'Set INVORA_E2E_ENV to an isolated development environment JSON file.');
const config:Record<string,string>=environmentPath?JSON.parse(readFileSync(environmentPath,'utf8')):{};
const credentials={login:'browser-owner',password:'Browser-test-password-2026'};
let token='',branch='',customer='',product='',supplier='';const imei=String(Date.now()).padStart(15,'3');
test.beforeAll(async({request})=>{
 const session=await ownerSession(request,{tradeName:'Invora Test Store',branchCode:'MAIN',branchName:'Main store',ownerLogin:credentials.login,ownerName:'Test Owner',password:credentials.password});token=session.accessToken;branch=session.user.branchIds[0];
 const post=async(path:string,data:unknown)=>{const r=await request.post('/api/v1'+path,{headers:{Authorization:'Bearer '+token,'Idempotency-Key':crypto.randomUUID()},data});expect(r.ok(),await r.text()).toBeTruthy();return r.json();};
 const tax=await post('/tax-rates',{name:'Browser zero tax',rate:'0',cessRate:'0'});
 product=await post('/products',{name:'A6 Pro',brand:'Oppo',category:'Smartphone',hsn:'85171300',taxRateId:tax,sku:'BROWSER-'+Date.now(),barcode:null,ram:'8GB',storage:'128GB',color:'Green',serialized:true,sellingPrice:'3000',mrp:'3500',warrantyMonths:12});
 supplier=await post('/suppliers',{name:'Browser Supplier',phone:'9000000009',stateCode:'23'});
 customer=await post('/customers',{name:'Browser Customer '+imei,phone:'9000000008',stateCode:'23'});
 await post('/inventory/adjustments',{branchId:branch,productVariantId:product,quantity:1,unitCost:'1000',reason:'Isolated browser-test opening stock',devices:[{imei1:imei}]});
});
test.beforeEach(async({page})=>{await page.goto('/login');await page.getByLabel('Login',{exact:true}).fill(credentials.login);await page.getByLabel('Password',{exact:true}).fill(credentials.password);await page.getByRole('button',{name:'Sign in →'}).click();await expect(page.getByRole('heading',{level:1})).toBeVisible();await expect(page).toHaveURL(/\/$/);});
test('scanner sale posts, refresh restores session, credit note and refund reconcile',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/sales/new');
 await page.getByRole('textbox',{name:'Scan IMEI, serial or barcode'}).fill(imei);await page.getByRole('textbox',{name:'Scan IMEI, serial or barcode'}).press('Enter');await expect(page.locator('tbody')).toContainText(imei);
 await page.getByRole('searchbox',{name:'Find customer',exact:true}).fill('Browser Customer '+imei);await page.locator('.contact-results').getByRole('button',{name:new RegExp(imei)}).click();await expect(page.getByRole('combobox',{name:'Customer',exact:true})).toHaveValue(customer);await page.getByLabel('Cash received').fill('3000');await page.getByRole('button',{name:'Review totals',exact:true}).click();await page.getByRole('button',{name:'Complete sale',exact:true}).click();await expect(page).toHaveURL(/\/sales\/[0-9a-f-]+$/);await expect(page.getByRole('heading',{level:1})).toContainText('INV-');
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Download invoice'}).click();expect((await download).suggestedFilename()).toMatch(/\.pdf$/);
 await page.reload();await expect(page.getByRole('heading',{level:1})).toContainText('INV-');await page.getByRole('button',{name:'Return items',exact:true}).click();await page.getByLabel('Reason',{exact:true}).fill('Browser return test');await page.getByLabel('Return quantity').fill('1');await page.getByRole('button',{name:'Confirm correction'}).click();await expect(page.locator('.page-intro .badge')).toHaveText('Returned');await expect(page.getByRole('dialog')).toHaveCount(0);
 await page.goto('/payments/new?partyId='+customer+'&kind=customer');await page.getByRole('combobox',{name:'Payment purpose',exact:true}).selectOption('refund');await page.getByLabel('Amount',{exact:true}).fill('3000');await page.getByRole('button',{name:/Record refund|Record payment|Confirm payment/}).click();await expect(page).toHaveURL(/\/payments$/);expect(errors).toEqual([]);
});
test('all authorized workspace screens load without runtime errors',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));for(const route of ['inventory','catalog','sales','purchases','customers','suppliers','lenden','payments','transfers','used-devices','expenses','reports','staff','audit','settings','account']){await page.goto('/'+route);await expect(page).toHaveURL(new RegExp('/'+route+'$'));await expect(page.getByRole('heading',{level:1})).toBeVisible();await expect(page.locator('p.error').filter({hasText:/./})).toHaveCount(0);}expect(errors).toEqual([]);
 await page.goto('/');await expect(page.locator('.hero-kpi h2')).not.toHaveText('');await page.screenshot({path:'../artifacts/workspace-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});await page.goto('/inventory');await page.getByRole('button',{name:'Toggle navigation'}).click();await expect(page.getByRole('link',{name:'LenDen',exact:true})).toBeVisible();await page.getByRole('link',{name:'LenDen',exact:true}).click();await expect(page.getByRole('heading',{name:'LenDen',exact:true})).toBeVisible();await page.waitForFunction(()=>document.querySelector('.sidebar')!.getBoundingClientRect().right<=0);await page.screenshot({path:'../artifacts/workspace-mobile.png',fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
});

test('purchase receiving captures devices and vendor return keeps the bill attached',async({page})=>{
 const receivedImei=String(BigInt(imei)+1n);await page.goto('/purchases/new');await page.getByRole('combobox',{name:'Product',exact:true}).selectOption(product);await page.getByRole('button',{name:'+ Add product',exact:true}).click();await page.getByRole('spinbutton',{name:'Item price'}).fill('1000');await page.getByRole('textbox',{name:'Scan IMEI, serial or barcode'}).fill(receivedImei);await page.getByRole('textbox',{name:'Scan IMEI, serial or barcode'}).press('Enter');await expect(page.locator('tbody')).toContainText(receivedImei);await page.getByRole('combobox',{name:'Supplier',exact:true}).selectOption(supplier);await page.getByLabel('Supplier invoice number').fill('BROWSER-VENDOR-'+Date.now());await page.getByRole('button',{name:'Review totals',exact:true}).click();await page.getByRole('button',{name:'Complete purchase',exact:true}).click();await expect(page).toHaveURL(/\/purchases\/[0-9a-f-]+$/);
 await page.locator('invora-attachments input[type=file]').setInputFiles({name:'vendor.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.7\nBrowser-only attachment')});await expect(page.locator('invora-attachments')).toContainText('vendor.pdf');await page.getByRole('button',{name:'Supplier return',exact:true}).click();await page.getByLabel('Reason',{exact:true}).fill('Wrong color, physically returned');await page.getByLabel('Supplier credit-note reference').fill('VENDOR-CREDIT-'+Date.now());await page.getByLabel('Return quantity').fill('1');await page.getByRole('combobox',{name:'Device being returned',exact:true}).selectOption({label:receivedImei});await page.getByRole('button',{name:'Confirm correction'}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.locator('tbody tr').first()).toContainText('1');await expect(page.locator('p.error').filter({hasText:/./})).toHaveCount(0);
});
